import { AlertTriangle, CheckCircle2, Dumbbell } from "lucide-react";

import type {
  DashboardFilter,
  NeedAssignmentItem,
  RecentDoneItem,
  SecondaryCheckItem,
  SummaryMetric,
  TrainerOperatingClient,
  WaitingReviewItem,
} from "./types";

export const dashboardFilters: Array<{ id: DashboardFilter; label: string }> = [
  { id: "all", label: "Все" },
  { id: "needs_action", label: "Требуют действия" },
  { id: "needs_assignment", label: "Без следующей тренировки" },
  { id: "waiting_review", label: "Ждут разбора" },
  { id: "planned_today", label: "Сегодня по плану" },
  { id: "on_track", label: "Идут по плану" },
];

export const trainerOperatingClients: TrainerOperatingClient[] = [
  {
    id: "artem-smirnov",
    name: "Артем Смирнов",
    initials: "АС",
    goal: "Набор массы",
    todayState: "Завершил жимовой день 2 часа назад",
    nextWorkout: null,
    lastWorkout: { name: "Жимовой день", meta: "Сегодня", detail: "RPE 9, жим -2 повтора" },
    status: "waiting_review",
    priority: "high",
    plannedToday: true,
    action: "open_review",
    actionLabel: "Разобрать",
    secondaryLabel: "Открыть",
    secondaryHref: "/trainer/clients/artem-smirnov",
    reviewHref: "/trainer/review/artem-smirnov-2026-06-10",
    reason: "Тренировка требует разбора до следующего назначения.",
    coachNote: "Высокий RPE и просадка в жиме. Нужна короткая обратная связь.",
    recommendedTemplate: "Тяговой день",
    rpe: "9",
  },
  {
    id: "egor-nikitin",
    name: "Егор Никитин",
    initials: "ЕН",
    goal: "Рекомпозиция",
    todayState: "Новый клиент, анкета заполнена",
    nextWorkout: null,
    lastWorkout: null,
    status: "no_program",
    priority: "high",
    plannedToday: false,
    action: "quick_assign",
    actionLabel: "Назначить",
    secondaryLabel: "Открыть",
    secondaryHref: "/trainer/clients/egor-nikitin",
    reason: "Нет стартовой тренировки и активной структуры.",
    coachNote: "Лучше назначить короткую тренировку на все тело, чтобы клиент начал сегодня.",
    recommendedTemplate: "Старт на все тело",
  },
  {
    id: "sofia-andreeva",
    name: "София Андреева",
    initials: "СА",
    goal: "Сила без боли",
    todayState: "Сообщила о боли в плече",
    nextWorkout: { name: "Верх тела техника", meta: "Завтра", detail: "Нужна корректировка" },
    lastWorkout: { name: "Тяговой день", meta: "3 дня назад", detail: "Боль 3/10" },
    status: "needs_correction",
    priority: "high",
    plannedToday: false,
    action: "open_client",
    actionLabel: "Открыть",
    secondaryLabel: "Сообщение",
    secondaryHref: "/trainer/messages",
    messageHref: "/trainer/messages",
    reason: "Пожаловалась на плечо после тяговой тренировки.",
    coachNote: "Нужно уточнить симптомы и заменить жимовые движения перед следующей тренировкой.",
    recommendedTemplate: "Верх без нагрузки на плечо",
  },
  {
    id: "maria-volkova",
    name: "Мария Волкова",
    initials: "МВ",
    goal: "Снижение веса",
    todayState: "Ноги + кор запланирована сегодня",
    nextWorkout: { name: "Ноги + кор", meta: "Сегодня", detail: "52 мин" },
    lastWorkout: { name: "Верх тела", meta: "Вчера", detail: "Все подходы закрыты" },
    status: "on_track",
    priority: "low",
    plannedToday: true,
    action: "open_client",
    actionLabel: "Открыть",
    secondaryLabel: "Сообщение",
    secondaryHref: "/trainer/messages",
    reason: "План на сегодня есть, клиент в ритме.",
    coachNote: "Только проверить комментарий после выполнения.",
    recommendedTemplate: "Ноги + кор",
    rpe: "7",
  },
  {
    id: "irina-kozlova",
    name: "Ирина Козлова",
    initials: "ИК",
    goal: "Сила и техника",
    todayState: "Сегодня восстановление",
    nextWorkout: { name: "Тяга техника", meta: "Завтра", detail: "Контроль лопаток" },
    lastWorkout: { name: "Верх тела техника", meta: "3 дня назад", detail: "RPE 7" },
    status: "on_track",
    priority: "low",
    plannedToday: false,
    action: "open_client",
    actionLabel: "Открыть",
    secondaryLabel: "Сообщение",
    secondaryHref: "/trainer/messages",
    reason: "Следующая тренировка назначена.",
    coachNote: "Можно оставить текущий темп.",
    recommendedTemplate: "Тяга техника",
  },
  {
    id: "dmitry-lebedev",
    name: "Дмитрий Лебедев",
    initials: "ДЛ",
    goal: "Вернуть ритм",
    todayState: "После командировки без плана",
    nextWorkout: { name: "Возврат на все тело", meta: "Пятница", detail: "Мягкий вход" },
    lastWorkout: { name: "Все тело", meta: "6 дней назад", detail: "Сокращенный объем" },
    status: "on_track",
    priority: "low",
    plannedToday: false,
    action: "open_client",
    actionLabel: "Открыть",
    secondaryLabel: "Открыть",
    secondaryHref: "/trainer/clients/dmitry-lebedev",
    reason: "Следующий шаг после паузы уже назначен.",
    coachNote: "Назначить короткую тренировку на все тело без отказных подходов.",
    recommendedTemplate: "Возврат на все тело",
  },
  {
    id: "olga-kuznetsova",
    name: "Ольга Кузнецова",
    initials: "ОК",
    goal: "Тонус и осанка",
    todayState: "Чек-ин отправлен утром",
    nextWorkout: { name: "Осанка + ягодицы", meta: "Завтра", detail: "45 мин" },
    lastWorkout: { name: "Мобильность и сила", meta: "2 дня назад", detail: "RPE 6" },
    status: "on_track",
    priority: "low",
    plannedToday: false,
    action: "open_client",
    actionLabel: "Открыть",
    secondaryLabel: "Сообщение",
    secondaryHref: "/trainer/messages",
    reason: "Все назначено, нужна только проверка чек-ина позже.",
    coachNote: "Хороший ритм, не трогать нагрузку.",
    recommendedTemplate: "Осанка + ягодицы",
  },
  {
    id: "maxim-orlov",
    name: "Максим Орлов",
    initials: "МО",
    goal: "Силовой блок",
    todayState: "День жима завершен утром",
    nextWorkout: { name: "День приседа", meta: "Пятница", detail: "5 упражнений" },
    lastWorkout: { name: "День жима", meta: "Сегодня", detail: "Лучший сет 105 x 4" },
    status: "on_track",
    priority: "low",
    plannedToday: true,
    action: "open_client",
    actionLabel: "Открыть",
    secondaryLabel: "Открыть",
    secondaryHref: "/trainer/clients/maxim-orlov",
    reviewHref: "/trainer/review/maxim-orlov-2026-06-18",
    reason: "Следующий шаг назначен, разбор можно сделать позже.",
    coachNote: "Проверить технику перед пятничным приседом.",
    recommendedTemplate: "День приседа",
    rpe: "8",
  },
  {
    id: "anna-sokolova",
    name: "Анна Соколова",
    initials: "АС",
    goal: "Форма 3x45",
    todayState: "Тренировка назначена на вечер",
    nextWorkout: { name: "Все тело 45", meta: "Сегодня 19:00", detail: "3 круга" },
    lastWorkout: { name: "Все тело 45", meta: "2 дня назад", detail: "Без пропусков" },
    status: "on_track",
    priority: "low",
    plannedToday: true,
    action: "open_client",
    actionLabel: "Открыть",
    secondaryLabel: "Сообщение",
    secondaryHref: "/trainer/messages",
    reason: "План есть, задача не требует вмешательства.",
    coachNote: "Можно проверить самочувствие после вечерней тренировки.",
    recommendedTemplate: "Все тело 45",
  },
  {
    id: "roman-belov",
    name: "Роман Белов",
    initials: "РБ",
    goal: "Минус 8 кг",
    todayState: "Нет тренировки после вчерашнего кардио",
    nextWorkout: { name: "Ноги умеренно", meta: "Суббота", detail: "Без осевого перегруза" },
    lastWorkout: { name: "Кардио зона 2", meta: "Вчера", detail: "38 мин" },
    status: "on_track",
    priority: "low",
    plannedToday: false,
    action: "open_client",
    actionLabel: "Открыть",
    secondaryLabel: "Открыть",
    secondaryHref: "/trainer/clients/roman-belov",
    reason: "Следующая силовая назначена.",
    coachNote: "Подойдет тренировка ног без большого осевого стресса.",
    recommendedTemplate: "Ноги умеренно",
  },
  {
    id: "nikita-fedorov",
    name: "Никита Федоров",
    initials: "НФ",
    goal: "Набор мышц",
    todayState: "Тяговой день запланирован завтра",
    nextWorkout: { name: "Тяговой день", meta: "Завтра", detail: "Спина + бицепс" },
    lastWorkout: { name: "Жимовой день", meta: "Вчера", detail: "RPE 8" },
    status: "on_track",
    priority: "low",
    plannedToday: false,
    action: "open_client",
    actionLabel: "Открыть",
    secondaryLabel: "Сообщение",
    secondaryHref: "/trainer/messages",
    reason: "План есть, прогресс идет по графику.",
    coachNote: "Проверить только сон в следующем чек-ине.",
    recommendedTemplate: "Тяговой день",
  },
  {
    id: "elena-tarasova",
    name: "Елена Тарасова",
    initials: "ЕТ",
    goal: "Функциональная сила",
    todayState: "Без активного блока после отпуска",
    nextWorkout: { name: "Перезапуск на все тело", meta: "Пятница", detail: "Оценка весов" },
    lastWorkout: { name: "Ноги + кор", meta: "12 дней назад", detail: "Перед отпуском" },
    status: "on_track",
    priority: "low",
    plannedToday: false,
    action: "open_client",
    actionLabel: "Открыть",
    secondaryLabel: "Открыть",
    secondaryHref: "/trainer/clients/elena-tarasova",
    reason: "Перезапуск тренировочного ритма назначен.",
    coachNote: "Начать с оценки рабочих весов, не с полного объема.",
    recommendedTemplate: "Перезапуск на все тело",
  },
  {
    id: "pavel-ivanov",
    name: "Павел Иванов",
    initials: "ПИ",
    goal: "Подготовка к старту",
    todayState: "Темповая работа вечером",
    nextWorkout: { name: "Темповые ноги", meta: "Сегодня 18:30", detail: "Контроль скорости" },
    lastWorkout: { name: "Силовой верх", meta: "2 дня назад", detail: "Все по плану" },
    status: "on_track",
    priority: "low",
    plannedToday: true,
    action: "open_client",
    actionLabel: "Открыть",
    secondaryLabel: "Сообщение",
    secondaryHref: "/trainer/messages",
    reason: "Назначение есть, вмешательство не требуется.",
    coachNote: "Проверить скорость подходов после выполнения.",
    recommendedTemplate: "Темповые ноги",
  },
  {
    id: "liza-gromova",
    name: "Лиза Громова",
    initials: "ЛГ",
    goal: "Рекомпозиция",
    todayState: "Утром завершила ноги",
    nextWorkout: { name: "Верх тела", meta: "Суббота", detail: "После разбора ног" },
    lastWorkout: { name: "Ноги", meta: "Сегодня", detail: "RPE 8, тяга +5 кг" },
    status: "on_track",
    priority: "low",
    plannedToday: true,
    action: "open_client",
    actionLabel: "Открыть",
    secondaryLabel: "Открыть",
    secondaryHref: "/trainer/clients/liza-gromova",
    reviewHref: "/trainer/review/liza-gromova-2026-06-18",
    reason: "Следующий шаг назначен, разбор можно сделать позже.",
    coachNote: "После разбора оставить верх тела на субботу.",
    recommendedTemplate: "Верх тела",
    rpe: "8",
  },
  {
    id: "katya-morozova",
    name: "Екатерина Морозова",
    initials: "ЕМ",
    goal: "Гипертрофия",
    todayState: "Нижняя часть тела завтра",
    nextWorkout: { name: "Ноги", meta: "Завтра", detail: "4 упражнения" },
    lastWorkout: { name: "Силовой верх", meta: "5 дней назад", detail: "RPE 8" },
    status: "on_track",
    priority: "low",
    plannedToday: false,
    action: "open_client",
    actionLabel: "Открыть",
    secondaryLabel: "Сообщение",
    secondaryHref: "/trainer/messages",
    reason: "Следующий тренировочный шаг назначен.",
    coachNote: "Проверить выполнение завтра вечером.",
    recommendedTemplate: "Ноги",
  },
  {
    id: "vadim-rybakov",
    name: "Вадим Рыбаков",
    initials: "ВР",
    goal: "Снижение веса",
    todayState: "Кардио в зоне 2 сегодня",
    nextWorkout: { name: "Кардио зона 2", meta: "Сегодня", detail: "35 минут" },
    lastWorkout: { name: "Легкая тренировка на все тело", meta: "2 дня назад", detail: "RPE 6" },
    status: "on_track",
    priority: "low",
    plannedToday: true,
    action: "open_client",
    actionLabel: "Открыть",
    secondaryLabel: "Сообщение",
    secondaryHref: "/trainer/messages",
    reason: "План на сегодня есть.",
    coachNote: "Не менять нагрузку.",
    recommendedTemplate: "Кардио зона 2",
  },
  {
    id: "alina-petrova",
    name: "Алина Петрова",
    initials: "АП",
    goal: "Тонус",
    todayState: "Отдых после тренировки на все тело",
    nextWorkout: { name: "Ягодицы + кор", meta: "Пятница", detail: "45 минут" },
    lastWorkout: { name: "Все тело", meta: "Вчера", detail: "Все закрыто" },
    status: "on_track",
    priority: "low",
    plannedToday: false,
    action: "open_client",
    actionLabel: "Открыть",
    secondaryLabel: "Сообщение",
    secondaryHref: "/trainer/messages",
    reason: "Следующая тренировка назначена.",
    coachNote: "Клиент идет спокойно.",
    recommendedTemplate: "Ягодицы + кор",
  },
  {
    id: "sergey-mikhailov",
    name: "Сергей Михайлов",
    initials: "СМ",
    goal: "Сила",
    todayState: "Присед в пятницу",
    nextWorkout: { name: "Силовой присед", meta: "Пятница", detail: "Основной сет 120 x 5" },
    lastWorkout: { name: "Объемный жим", meta: "Вчера", detail: "RPE 8" },
    status: "on_track",
    priority: "low",
    plannedToday: false,
    action: "open_client",
    actionLabel: "Открыть",
    secondaryLabel: "Сообщение",
    secondaryHref: "/trainer/messages",
    reason: "План есть, вмешательство не требуется.",
    coachNote: "Смотреть восстановление перед приседом.",
    recommendedTemplate: "Силовой присед",
  },
  {
    id: "yana-vasilieva",
    name: "Яна Васильева",
    initials: "ЯВ",
    goal: "Рекомпозиция",
    todayState: "Верх тела сегодня вечером",
    nextWorkout: { name: "Верх тела", meta: "Сегодня 20:00", detail: "50 минут" },
    lastWorkout: { name: "Ноги", meta: "2 дня назад", detail: "RPE 7" },
    status: "on_track",
    priority: "low",
    plannedToday: true,
    action: "open_client",
    actionLabel: "Открыть",
    secondaryLabel: "Сообщение",
    secondaryHref: "/trainer/messages",
    reason: "План на сегодня есть.",
    coachNote: "Можно не трогать.",
    recommendedTemplate: "Верх тела",
  },
  {
    id: "timur-akimov",
    name: "Тимур Акимов",
    initials: "ТА",
    goal: "Набор массы",
    todayState: "Отдых после ног",
    nextWorkout: { name: "Верх объем", meta: "Завтра", detail: "Грудь + спина" },
    lastWorkout: { name: "Ноги", meta: "Вчера", detail: "RPE 8" },
    status: "on_track",
    priority: "low",
    plannedToday: false,
    action: "open_client",
    actionLabel: "Открыть",
    secondaryLabel: "Сообщение",
    secondaryHref: "/trainer/messages",
    reason: "Следующая тренировка назначена.",
    coachNote: "План стабильный, вмешательство не нужно.",
    recommendedTemplate: "Верх объем",
  },
];

export const statusOrder: Record<TrainerOperatingClient["status"], number> = {
  waiting_review: 1,
  needs_assignment: 2,
  no_program: 2,
  needs_correction: 3,
  missed_workout: 3,
  on_track: 5,
};

export function sortClientsForBoard(clients: TrainerOperatingClient[]) {
  const priorityScore: Record<TrainerOperatingClient["priority"], number> = {
    high: 0,
    medium: 1,
    low: 2,
  };

  return [...clients].sort((a, b) => {
    const priorityDiff = priorityScore[a.priority] - priorityScore[b.priority];
    if (priorityDiff !== 0) return priorityDiff;

    const statusDiff = statusOrder[a.status] - statusOrder[b.status];
    if (statusDiff !== 0) return statusDiff;

    if (a.plannedToday !== b.plannedToday) return a.plannedToday ? -1 : 1;
    return a.name.localeCompare(b.name, "ru");
  });
}

export function filterClients(clients: TrainerOperatingClient[], filter: DashboardFilter) {
  switch (filter) {
    case "needs_action":
      return clients.filter((client) => client.status !== "on_track");
    case "needs_assignment":
      return clients.filter((client) => client.status === "needs_assignment" || client.status === "no_program");
    case "waiting_review":
      return clients.filter((client) => client.status === "waiting_review");
    case "planned_today":
      return clients.filter((client) => client.plannedToday);
    case "on_track":
      return clients.filter((client) => client.status === "on_track");
    default:
      return clients;
  }
}

export function buildSummaryMetrics(clients: TrainerOperatingClient[]): SummaryMetric[] {
  const needAction = clients.filter((client) => client.status !== "on_track").length;
  const needAssignment = clients.filter((client) => client.status === "needs_assignment" || client.status === "no_program").length;
  const waitingReview = clients.filter((client) => client.status === "waiting_review").length;
  const missedWorkout = clients.filter((client) => client.status === "missed_workout").length;

  return [
    { id: "active", label: "Активных клиентов", value: clients.length, icon: CheckCircle2, tone: "neutral" },
    { id: "action", label: "Требуют действия", value: needAction, icon: AlertTriangle, tone: "amber" },
    { id: "assignment", label: "Без шага", value: needAssignment, icon: Dumbbell, tone: "lime" },
    { id: "review", label: "Ждут разбора", value: waitingReview, icon: CheckCircle2, tone: "cyan" },
    { id: "missed", label: "Пропуски", value: missedWorkout, icon: AlertTriangle, tone: "red" },
  ];
}

export function buildWaitingReviews(clients: TrainerOperatingClient[]): WaitingReviewItem[] {
  return clients
    .filter((client) => client.status === "waiting_review")
    .map((client) => ({
      id: `review-${client.id}`,
      clientId: client.id,
      client: client.name,
      workout: client.lastWorkout?.name ?? "Workout",
      completedAt: client.lastWorkout?.meta ?? "Сегодня",
      rpe: client.rpe ?? "—",
      signal: client.lastWorkout?.detail ?? client.reason,
      href: client.reviewHref ?? `/trainer/review/${client.id}-mock`,
    }));
}

export function buildNeedAssignments(clients: TrainerOperatingClient[]): NeedAssignmentItem[] {
  return clients
    .filter((client) => client.status === "needs_assignment" || client.status === "no_program")
    .map((client) => ({
      id: `assign-${client.id}`,
      clientId: client.id,
      client: client.name,
      reason: client.reason,
      recommendedTemplate: client.recommendedTemplate ?? "Full Body",
    }));
}

export const recentDoneItems: RecentDoneItem[] = [
  {
    id: "done-maria",
    time: "09:20",
    label: "Мария Волкова",
    detail: "План на сегодня проверен, изменений не требуется.",
  },
  {
    id: "done-olga",
    time: "09:05",
    label: "Ольга Кузнецова",
    detail: "Чек-ин прочитан, следующий день остается без изменений.",
  },
  {
    id: "done-nikita",
    time: "08:48",
    label: "Никита Федоров",
    detail: "Pull Day подтвержден на завтра.",
  },
];

export const secondaryCheckItems: SecondaryCheckItem[] = [
  {
    id: "measurements",
    label: "Нет замеров",
    count: 4,
    helper: "Можно запросить позже, не блокирует тренировку.",
  },
  {
    id: "checkins",
    label: "Не проходили чек-ин",
    count: 2,
    helper: "Проверить после основных действий.",
  },
  {
    id: "weight",
    label: "Не обновляли вес",
    count: 3,
    helper: "Важно для корректировки недели.",
  },
  {
    id: "messages",
    label: "Не ответили в сообщении",
    count: 1,
    helper: "Мягкий follow-up без срочности.",
  },
];
