import type { AthleteAchievement } from "./types";

export type AchievementCatalogItem = {
  collectionId: string;
  levelId: string;
  categoryLabel: string;
  category: AthleteAchievement["category"];
  collection: string;
  tierLabel: string;
  tier: NonNullable<AthleteAchievement["tier"]>;
  title: string;
  description: string;
  threshold: string;
  score: number;
  version: string;
  catalogStatus: string;
  rarity: AthleteAchievement["rarity"];
  assetSrc: string;
};

export const achievementCatalog: AchievementCatalogItem[] = [
  {
    collectionId: "START-FIRST-WORKOUT",
    levelId: "START-FIRST-WORKOUT-BRONZE",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Первый шаг",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Первый шаг",
    description: "Завершить первую тренировку",
    threshold: "1",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/01-pervyi-shag.png",
  },
  {
    collectionId: "START-FIRST-WEEK",
    levelId: "START-FIRST-WEEK-BRONZE",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Первая неделя",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Первый ритм",
    description: "Выполнить 3 тренировки за первую неделю",
    threshold: "3",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/02-pervyi-ritm.png",
  },
  {
    collectionId: "START-FIRST-PR",
    levelId: "START-FIRST-PR-BRONZE",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Первый PR",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Первая победа",
    description: "Поставить первый личный рекорд",
    threshold: "1",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/03-pervaya-pobeda.png",
  },
  {
    collectionId: "START-FIRST-CHECKIN",
    levelId: "START-FIRST-CHECKIN-BRONZE",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Первый контроль",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "На пути к цели",
    description: "Заполнить чек-ин и первые замеры",
    threshold: "1",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/04-na-puti-k-tseli.png",
  },
  {
    collectionId: "START-TEAM-JOIN",
    levelId: "START-TEAM-JOIN-BRONZE",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Вступление в команду",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Часть команды",
    description: "Принять приглашение тренера и активировать профиль",
    threshold: "1",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/05-chast-komandy.png",
  },
  {
    collectionId: "START-FIRST-CYCLE",
    levelId: "START-FIRST-CYCLE-BRONZE",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Первый микроцикл",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Первый микроцикл",
    description: "Завершить первый тренировочный микроцикл",
    threshold: "1",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/06-pervyi-mikrotsikl.png",
  },
  {
    collectionId: "DISC-STREAK",
    levelId: "DISC-STREAK-BRONZE",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Серия тренировок",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "В ритме",
    description: "7 тренировок подряд",
    threshold: "7",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/07-v-ritme.png",
  },
  {
    collectionId: "DISC-STREAK",
    levelId: "DISC-STREAK-SILVER",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Серия тренировок",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Не сбавляя темп",
    description: "21 тренировка подряд",
    threshold: "21",
    score: 25,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/08-ne-sbavlyaya-temp.png",
  },
  {
    collectionId: "DISC-STREAK",
    levelId: "DISC-STREAK-GOLD",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Серия тренировок",
    tierLabel: "Золото",
    tier: "gold",
    title: "Железная привычка",
    description: "60 тренировок подряд",
    threshold: "60",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/09-pervye-shagi.png",
  },
  {
    collectionId: "DISC-STREAK",
    levelId: "DISC-STREAK-MASTER",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Серия тренировок",
    tierLabel: "Мастер",
    tier: "master",
    title: "Годовой ритм",
    description: "120 тренировок подряд",
    threshold: "120",
    score: 100,
    version: "Later",
    catalogStatus: "Спорно",
    rarity: "epic",
    assetSrc: "/achievements/v1/10-uzhe-opytnyi.png",
  },
  {
    collectionId: "DISC-WORKOUTS",
    levelId: "DISC-WORKOUTS-BRONZE",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Выполненные тренировки",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Первые шаги",
    description: "10 завершённых тренировок",
    threshold: "10",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/11-zheleznaya-privychka.png",
  },
  {
    collectionId: "DISC-WORKOUTS",
    levelId: "DISC-WORKOUTS-SILVER",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Выполненные тренировки",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Уже опытный",
    description: "50 завершённых тренировок",
    threshold: "50",
    score: 25,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/12-godovoy-ritm.png",
  },
  {
    collectionId: "DISC-WORKOUTS",
    levelId: "DISC-WORKOUTS-GOLD",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Выполненные тренировки",
    tierLabel: "Золото",
    tier: "gold",
    title: "В хорошей форме",
    description: "70 завершённых тренировок",
    threshold: "70",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/13-v-horoshey-forme.png",
  },
  {
    collectionId: "DISC-WORKOUTS",
    levelId: "DISC-WORKOUTS-MASTER",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Выполненные тренировки",
    tierLabel: "Мастер",
    tier: "master",
    title: "Машина тренировок",
    description: "120 завершённых тренировок",
    threshold: "120",
    score: 100,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/14-mashina-trenirovok.png",
  },
  {
    collectionId: "DISC-WEEKS",
    levelId: "DISC-WEEKS-BRONZE",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Тренировочные недели",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Первый цикл",
    description: "4 недели с выполненными тренировками",
    threshold: "4",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/15-pervyi-cikl.png",
  },
  {
    collectionId: "DISC-WEEKS",
    levelId: "DISC-WEEKS-SILVER",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Тренировочные недели",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Уже привычка",
    description: "12 недель с выполненными тренировками",
    threshold: "12",
    score: 25,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/16-uzhe-privychka.png",
  },
  {
    collectionId: "DISC-WEEKS",
    levelId: "DISC-WEEKS-GOLD",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Тренировочные недели",
    tierLabel: "Золото",
    tier: "gold",
    title: "Система работает",
    description: "24 недели с выполненными тренировками",
    threshold: "24",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/17-sistema-rabotaet.png",
  },
  {
    collectionId: "DISC-WEEKS",
    levelId: "DISC-WEEKS-MASTER",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Тренировочные недели",
    tierLabel: "Мастер",
    tier: "master",
    title: "Год в системе",
    description: "52 недели с выполненными тренировками",
    threshold: "52",
    score: 100,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/18-god-v-sisteme.png",
  },
  {
    collectionId: "DISC-CHECKINS",
    levelId: "DISC-CHECKINS-BRONZE",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Чек-ины",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "На связи",
    description: "10 чек-инов",
    threshold: "10",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/19-na-svyazi.png",
  },
  {
    collectionId: "DISC-CHECKINS",
    levelId: "DISC-CHECKINS-SILVER",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Чек-ины",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Ответственный",
    description: "30 чек-инов",
    threshold: "30",
    score: 25,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/20-otvetstvennyi.png",
  },
  {
    collectionId: "DISC-CHECKINS",
    levelId: "DISC-CHECKINS-GOLD",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Чек-ины",
    tierLabel: "Золото",
    tier: "gold",
    title: "Полное доверие",
    description: "50 чек-инов",
    threshold: "50",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/21-polnoe-doverie.png",
  },
  {
    collectionId: "DISC-CHECKINS",
    levelId: "DISC-CHECKINS-MASTER",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Чек-ины",
    tierLabel: "Мастер",
    tier: "master",
    title: "Всегда на связи",
    description: "100 чек-инов",
    threshold: "100",
    score: 100,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/22-vsegda-na-svyazi.png",
  },
  {
    collectionId: "DISC-MEASUREMENTS-RHYTHM",
    levelId: "DISC-MEASUREMENTS-RHYTHM-BRONZE",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Ритм замеров",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Ритм замеров",
    description: "4 недели с замерами по расписанию",
    threshold: "4",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/23-ritm-zamerov.png",
  },
  {
    collectionId: "DISC-MEASUREMENTS-RHYTHM",
    levelId: "DISC-MEASUREMENTS-RHYTHM-SILVER",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Ритм замеров",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Следит за динамикой",
    description: "8 недель с замерами по расписанию",
    threshold: "8",
    score: 25,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/24-sledit-za-dinamikoy.png",
  },
  {
    collectionId: "DISC-MEASUREMENTS-RHYTHM",
    levelId: "DISC-MEASUREMENTS-RHYTHM-GOLD",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Ритм замеров",
    tierLabel: "Золото",
    tier: "gold",
    title: "Контроль прогресса",
    description: "16 недель с замерами по расписанию",
    threshold: "16",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/25-kontrol-progressa.png",
  },
  {
    collectionId: "DISC-MEASUREMENTS-RHYTHM",
    levelId: "DISC-MEASUREMENTS-RHYTHM-MASTER",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Ритм замеров",
    tierLabel: "Мастер",
    tier: "master",
    title: "Дисциплина данных",
    description: "24 недели с замерами по расписанию",
    threshold: "24",
    score: 100,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/26-distsiplina-dannyh.png",
  },
  {
    collectionId: "DISC-PHOTOS-RHYTHM",
    levelId: "DISC-PHOTOS-RHYTHM-BRONZE",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Ритм фотоотчётов",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Фото по плану",
    description: "4 недели с фотоотчётами по расписанию",
    threshold: "4",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/27-foto-po-planu.png",
  },
  {
    collectionId: "DISC-PHOTOS-RHYTHM",
    levelId: "DISC-PHOTOS-RHYTHM-SILVER",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Ритм фотоотчётов",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Вижу путь",
    description: "8 недель с фотоотчётами по расписанию",
    threshold: "8",
    score: 25,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/28-vizhu-put.png",
  },
  {
    collectionId: "DISC-PHOTOS-RHYTHM",
    levelId: "DISC-PHOTOS-RHYTHM-GOLD",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Ритм фотоотчётов",
    tierLabel: "Золото",
    tier: "gold",
    title: "Регулярная хроника",
    description: "16 недель с фотоотчётами по расписанию",
    threshold: "16",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/29-regulyarnaya-hronika.png",
  },
  {
    collectionId: "DISC-PHOTOS-RHYTHM",
    levelId: "DISC-PHOTOS-RHYTHM-MASTER",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Ритм фотоотчётов",
    tierLabel: "Мастер",
    tier: "master",
    title: "Архив прогресса",
    description: "24 недели с фотоотчётами по расписанию",
    threshold: "24",
    score: 100,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/30-arhiv-progressa.png",
  },
  {
    collectionId: "DISC-RECS",
    levelId: "DISC-RECS-BRONZE",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Выполнение рекомендаций",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Слушаю тренера",
    description: "10 выполненных рекомендаций тренера",
    threshold: "10",
    score: 10,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/31-slushayu-trenera.png",
  },
  {
    collectionId: "DISC-RECS",
    levelId: "DISC-RECS-SILVER",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Выполнение рекомендаций",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Работаем вместе",
    description: "30 выполненных рекомендаций тренера",
    threshold: "30",
    score: 25,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/32-rabotaem-vmeste.png",
  },
  {
    collectionId: "DISC-RECS",
    levelId: "DISC-RECS-GOLD",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Выполнение рекомендаций",
    tierLabel: "Золото",
    tier: "gold",
    title: "Тренерский план принят",
    description: "60 выполненных рекомендаций тренера",
    threshold: "60",
    score: 50,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/33-trenerskiy-plan-prinyat.png",
  },
  {
    collectionId: "DISC-RECS",
    levelId: "DISC-RECS-MASTER",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Выполнение рекомендаций",
    tierLabel: "Мастер",
    tier: "master",
    title: "Идеальный ученик",
    description: "100 выполненных рекомендаций тренера",
    threshold: "100",
    score: 100,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/34-idealnyi-uchenik.png",
  },
  {
    collectionId: "DISC-RETURN",
    levelId: "DISC-RETURN-BRONZE",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Возвращение",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Вернулся",
    description: "Возврат после первой паузы больше 30 дней",
    threshold: "1",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/35-vernulsya.png",
  },
  {
    collectionId: "DISC-RETURN",
    levelId: "DISC-RETURN-SILVER",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Возвращение",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Не сдаюсь",
    description: "3 возвращения после паузы",
    threshold: "3",
    score: 25,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/36-ne-sdayus.png",
  },
  {
    collectionId: "DISC-RETURN",
    levelId: "DISC-RETURN-GOLD",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Возвращение",
    tierLabel: "Золото",
    tier: "gold",
    title: "Феникс",
    description: "5 возвращений после паузы",
    threshold: "5",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/37-feniks.png",
  },
  {
    collectionId: "DISC-RETURN",
    levelId: "DISC-RETURN-MASTER",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Возвращение",
    tierLabel: "Мастер",
    tier: "master",
    title: "Всегда поднимаюсь",
    description: "10 возвращений после паузы",
    threshold: "10",
    score: 100,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/38-vsegda-podnimayus.png",
  },
  {
    collectionId: "DISC-NO-MOVES",
    levelId: "DISC-NO-MOVES-BRONZE",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Без переносов",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "По расписанию",
    description: "10 тренировок без переноса",
    threshold: "10",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/39-po-raspisaniyu.png",
  },
  {
    collectionId: "DISC-NO-MOVES",
    levelId: "DISC-NO-MOVES-SILVER",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Без переносов",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Пунктуальность",
    description: "30 тренировок без переноса",
    threshold: "30",
    score: 25,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/40-punktualnost.png",
  },
  {
    collectionId: "DISC-NO-MOVES",
    levelId: "DISC-NO-MOVES-GOLD",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Без переносов",
    tierLabel: "Золото",
    tier: "gold",
    title: "Швейцарские часы",
    description: "60 тренировок без переноса",
    threshold: "60",
    score: 50,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/41-shveytsarskie-chasy.png",
  },
  {
    collectionId: "DISC-NO-MOVES",
    levelId: "DISC-NO-MOVES-MASTER",
    categoryLabel: "Дисциплина",
    category: "consistency",
    collection: "Без переносов",
    tierLabel: "Мастер",
    tier: "master",
    title: "Абсолютная дисциплина",
    description: "100 тренировок без переноса",
    threshold: "100",
    score: 100,
    version: "Later",
    catalogStatus: "Спорно",
    rarity: "epic",
    assetSrc: "/achievements/v1/42-absolyutnaya-distsiplina.png",
  },
  {
    collectionId: "STR-BENCH",
    levelId: "STR-BENCH-BRONZE",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Жим лёжа",
    tierLabel: "Кубок",
    tier: "cup",
    title: "Железная сотня",
    description: "Жим лёжа 100 кг",
    threshold: "100 кг",
    score: 50,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/43-zheleznaya-sotnya.png",
  },
  {
    collectionId: "STR-BENCH",
    levelId: "STR-BENCH-SILVER",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Жим лёжа",
    tierLabel: "Кубок",
    tier: "cup",
    title: "Серебряная штанга",
    description: "Жим лёжа 110 кг",
    threshold: "110 кг",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/44-serebryanaya-shtanga.png",
  },
  {
    collectionId: "STR-BENCH",
    levelId: "STR-BENCH-GOLD",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Жим лёжа",
    tierLabel: "Кубок",
    tier: "cup",
    title: "Золотой жим",
    description: "Жим лёжа 130 кг",
    threshold: "130 кг",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/45-zolotoy-zhim.png",
  },
  {
    collectionId: "STR-BENCH",
    levelId: "STR-BENCH-LEGENDARY",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Жим лёжа",
    tierLabel: "Легендарный кубок",
    tier: "cup",
    title: "Абсолют жима",
    description: "Жим лёжа 150 кг",
    threshold: "150 кг",
    score: 150,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/46-absolyut-zhima.png",
  },
  {
    collectionId: "STR-SQUAT",
    levelId: "STR-SQUAT-BRONZE",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Присед",
    tierLabel: "Кубок",
    tier: "cup",
    title: "Центнер",
    description: "Присед 100 кг",
    threshold: "100 кг",
    score: 50,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/47-tsentner.png",
  },
  {
    collectionId: "STR-SQUAT",
    levelId: "STR-SQUAT-SILVER",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Присед",
    tierLabel: "Кубок",
    tier: "cup",
    title: "Серебряный присед",
    description: "Присед 130 кг",
    threshold: "130 кг",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/48-serebryanyi-prised.png",
  },
  {
    collectionId: "STR-SQUAT",
    levelId: "STR-SQUAT-GOLD",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Присед",
    tierLabel: "Кубок",
    tier: "cup",
    title: "Золотой присед",
    description: "Присед 150 кг",
    threshold: "150 кг",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/49-zolotoy-prised.png",
  },
  {
    collectionId: "STR-SQUAT",
    levelId: "STR-SQUAT-LEGENDARY",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Присед",
    tierLabel: "Легендарный кубок",
    tier: "cup",
    title: "Король ног",
    description: "Присед 185 кг",
    threshold: "185 кг",
    score: 150,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/50-korol-nog.png",
  },
  {
    collectionId: "STR-DEADLIFT",
    levelId: "STR-DEADLIFT-BRONZE",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Становая тяга",
    tierLabel: "Кубок",
    tier: "cup",
    title: "Стальной старт",
    description: "Становая тяга 140 кг",
    threshold: "140 кг",
    score: 50,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/51-stalnoy-start.png",
  },
  {
    collectionId: "STR-DEADLIFT",
    levelId: "STR-DEADLIFT-SILVER",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Становая тяга",
    tierLabel: "Кубок",
    tier: "cup",
    title: "Железный позвоночник",
    description: "Становая тяга 180 кг",
    threshold: "180 кг",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/52-zheleznyi-pozvonochnik.png",
  },
  {
    collectionId: "STR-DEADLIFT",
    levelId: "STR-DEADLIFT-GOLD",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Становая тяга",
    tierLabel: "Кубок",
    tier: "cup",
    title: "Титан",
    description: "Становая тяга 220 кг",
    threshold: "220 кг",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/53-titan.png",
  },
  {
    collectionId: "STR-DEADLIFT",
    levelId: "STR-DEADLIFT-LEGENDARY",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Становая тяга",
    tierLabel: "Легендарный кубок",
    tier: "cup",
    title: "Повелитель тяги",
    description: "Становая тяга 240 кг",
    threshold: "240 кг",
    score: 150,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/54-povelitel-tyagi.png",
  },
  {
    collectionId: "STR-PULLUPS",
    levelId: "STR-PULLUPS-BRONZE",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Подтягивания",
    tierLabel: "Кубок",
    tier: "cup",
    title: "Турникмен",
    description: "10 подтягиваний",
    threshold: "10",
    score: 50,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/55-turnikmen.png",
  },
  {
    collectionId: "STR-PULLUPS",
    levelId: "STR-PULLUPS-SILVER",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Подтягивания",
    tierLabel: "Кубок",
    tier: "cup",
    title: "Повелитель турника",
    description: "15 подтягиваний",
    threshold: "15",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/56-povelitel-turnika.png",
  },
  {
    collectionId: "STR-PULLUPS",
    levelId: "STR-PULLUPS-GOLD",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Подтягивания",
    tierLabel: "Кубок",
    tier: "cup",
    title: "Гравитация бессильна",
    description: "20 подтягиваний",
    threshold: "20",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/57-gravitatsiya-bessilna.png",
  },
  {
    collectionId: "STR-PULLUPS",
    levelId: "STR-PULLUPS-LEGENDARY",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Подтягивания",
    tierLabel: "Легендарный кубок",
    tier: "cup",
    title: "Легенда турника",
    description: "30 подтягиваний",
    threshold: "30",
    score: 150,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/58-legenda-turnika.png",
  },
  {
    collectionId: "STR-PLANK",
    levelId: "STR-PLANK-BRONZE",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Планка",
    tierLabel: "Кубок",
    tier: "cup",
    title: "Камень",
    description: "Планка 2 минуты",
    threshold: "2 мин",
    score: 50,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/59-kamen.png",
  },
  {
    collectionId: "STR-PLANK",
    levelId: "STR-PLANK-SILVER",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Планка",
    tierLabel: "Кубок",
    tier: "cup",
    title: "Скала",
    description: "Планка 5 минут",
    threshold: "5 мин",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/60-skala.png",
  },
  {
    collectionId: "STR-PLANK",
    levelId: "STR-PLANK-GOLD",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Планка",
    tierLabel: "Кубок",
    tier: "cup",
    title: "Монолит",
    description: "Планка 10 минут",
    threshold: "10 мин",
    score: 50,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/61-monolit.png",
  },
  {
    collectionId: "STR-PLANK",
    levelId: "STR-PLANK-LEGENDARY",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Планка",
    tierLabel: "Легендарный кубок",
    tier: "cup",
    title: "Непоколебимый",
    description: "Планка 20 минут",
    threshold: "20 мин",
    score: 150,
    version: "Later",
    catalogStatus: "Спорно",
    rarity: "epic",
    assetSrc: "/achievements/v1/62-nepokolebimyi.png",
  },
  {
    collectionId: "STR-VOLUME",
    levelId: "STR-VOLUME-BRONZE",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Общий тоннаж",
    tierLabel: "Кубок",
    tier: "cup",
    title: "100 тонн",
    description: "Суммарный поднятый вес 100 тонн",
    threshold: "100 т",
    score: 50,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/63-100-tonn.png",
  },
  {
    collectionId: "STR-VOLUME",
    levelId: "STR-VOLUME-SILVER",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Общий тоннаж",
    tierLabel: "Кубок",
    tier: "cup",
    title: "500 тонн",
    description: "Суммарный поднятый вес 500 тонн",
    threshold: "500 т",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/64-500-tonn.png",
  },
  {
    collectionId: "STR-VOLUME",
    levelId: "STR-VOLUME-GOLD",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Общий тоннаж",
    tierLabel: "Кубок",
    tier: "cup",
    title: "1000 тонн",
    description: "Суммарный поднятый вес 1000 тонн",
    threshold: "1000 т",
    score: 50,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/65-1000-tonn.png",
  },
  {
    collectionId: "STR-VOLUME",
    levelId: "STR-VOLUME-LEGENDARY",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Общий тоннаж",
    tierLabel: "Легендарный кубок",
    tier: "cup",
    title: "Гора железа",
    description: "Суммарный поднятый вес 5000 тонн",
    threshold: "5000 т",
    score: 150,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/66-gora-zheleza.png",
  },
  {
    collectionId: "STR-SECRETS",
    levelId: "STR-SECRET-EXACT-100",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Секретные силовые",
    tierLabel: "Секретное",
    tier: "secret",
    title: "Идеальная сотня",
    description: "Жим ровно 100 кг",
    threshold: "100 кг",
    score: 25,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/67-idealnaya-sotnya.png",
  },
  {
    collectionId: "STR-SECRETS",
    levelId: "STR-SECRET-BW-BENCH",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Секретные силовые",
    tierLabel: "Секретное",
    tier: "secret",
    title: "Собственный вес",
    description: "Пожал штангу тяжелее собственного веса",
    threshold: "bodyweight",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/68-sobstvennyi-ves.png",
  },
  {
    collectionId: "STR-SECRETS",
    levelId: "STR-SECRET-FIRST-100",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Секретные силовые",
    tierLabel: "Секретное",
    tier: "secret",
    title: "Первый центнер",
    description: "Любое упражнение впервые достигло 100 кг",
    threshold: "100 кг",
    score: 25,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/69-pervyi-tsentner.png",
  },
  {
    collectionId: "STR-SECRETS",
    levelId: "STR-SECRET-3PRS",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Секретные силовые",
    tierLabel: "Секретное",
    tier: "secret",
    title: "День рекордов",
    description: "3 PR за одну тренировку",
    threshold: "3 PR",
    score: 50,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/70-den-rekordov.png",
  },
  {
    collectionId: "STR-SECRETS",
    levelId: "STR-SECRET-20PCT",
    categoryLabel: "Сила",
    category: "strength",
    collection: "Секретные силовые",
    tierLabel: "Секретное",
    tier: "secret",
    title: "Взрывной рост",
    description: "Повысить рабочий вес на 20% за цикл",
    threshold: "+20%",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/71-vzryvnoy-rost.png",
  },
  {
    collectionId: "TRANS-GOAL",
    levelId: "TRANS-GOAL-BRONZE",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Путь к цели",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Первый прогресс",
    description: "Выполнено 25% цели",
    threshold: "25%",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/72-pervyi-progress.png",
  },
  {
    collectionId: "TRANS-GOAL",
    levelId: "TRANS-GOAL-SILVER",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Путь к цели",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Уже близко",
    description: "Выполнено 50% цели",
    threshold: "50%",
    score: 25,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/73-uzhe-blizko.png",
  },
  {
    collectionId: "TRANS-GOAL",
    levelId: "TRANS-GOAL-GOLD",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Путь к цели",
    tierLabel: "Золото",
    tier: "gold",
    title: "Остался шаг",
    description: "Выполнено 75% цели",
    threshold: "75%",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/74-ostalsya-shag.png",
  },
  {
    collectionId: "TRANS-GOAL",
    levelId: "TRANS-GOAL-MASTER",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Путь к цели",
    tierLabel: "Мастер",
    tier: "master",
    title: "Цель достигнута",
    description: "Выполнено 100% цели",
    threshold: "100%",
    score: 100,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/75-tsel-dostignuta.png",
  },
  {
    collectionId: "TRANS-WEIGHTLOSS",
    levelId: "TRANS-WEIGHTLOSS-BRONZE",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Снижение веса",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Первый шаг вниз",
    description: "Выполнено 25% цели по снижению веса",
    threshold: "25%",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/76-pervyi-shag-vniz.png",
  },
  {
    collectionId: "TRANS-WEIGHTLOSS",
    levelId: "TRANS-WEIGHTLOSS-SILVER",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Снижение веса",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Движение к форме",
    description: "Выполнено 50% цели по снижению веса",
    threshold: "50%",
    score: 25,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/77-dvizhenie-k-forme.png",
  },
  {
    collectionId: "TRANS-WEIGHTLOSS",
    levelId: "TRANS-WEIGHTLOSS-GOLD",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Снижение веса",
    tierLabel: "Золото",
    tier: "gold",
    title: "Почти у цели",
    description: "Выполнено 75% цели по снижению веса",
    threshold: "75%",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/78-pochti-u-tseli.png",
  },
  {
    collectionId: "TRANS-WEIGHTLOSS",
    levelId: "TRANS-WEIGHTLOSS-MASTER",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Снижение веса",
    tierLabel: "Мастер",
    tier: "master",
    title: "Новый человек",
    description: "Выполнено 100% цели по снижению веса",
    threshold: "100%",
    score: 100,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/79-novyi-chelovek.png",
  },
  {
    collectionId: "TRANS-MASS",
    levelId: "TRANS-MASS-BRONZE",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Набор массы",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Первый прирост",
    description: "Выполнено 25% цели по набору массы",
    threshold: "25%",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/80-pervyi-prirost.png",
  },
  {
    collectionId: "TRANS-MASS",
    levelId: "TRANS-MASS-SILVER",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Набор массы",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Уже заметно",
    description: "Выполнено 50% цели по набору массы",
    threshold: "50%",
    score: 25,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/81-uzhe-zametno.png",
  },
  {
    collectionId: "TRANS-MASS",
    levelId: "TRANS-MASS-GOLD",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Набор массы",
    tierLabel: "Золото",
    tier: "gold",
    title: "Новая форма",
    description: "Выполнено 75% цели по набору массы",
    threshold: "75%",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/82-novaya-forma.png",
  },
  {
    collectionId: "TRANS-MASS",
    levelId: "TRANS-MASS-MASTER",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Набор массы",
    tierLabel: "Мастер",
    tier: "master",
    title: "Машина роста",
    description: "Выполнено 100% цели по набору массы",
    threshold: "100%",
    score: 100,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/83-mashina-rosta.png",
  },
  {
    collectionId: "TRANS-PHOTOS",
    levelId: "TRANS-PHOTOS-BRONZE",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Фото прогресса",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Первая трансформация",
    description: "5 фото прогресса",
    threshold: "5",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/84-pervaya-transformatsiya.png",
  },
  {
    collectionId: "TRANS-PHOTOS",
    levelId: "TRANS-PHOTOS-SILVER",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Фото прогресса",
    tierLabel: "Серебро",
    tier: "silver",
    title: "История изменений",
    description: "15 фото прогресса",
    threshold: "15",
    score: 25,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/85-istoriya-izmeneniy.png",
  },
  {
    collectionId: "TRANS-PHOTOS",
    levelId: "TRANS-PHOTOS-GOLD",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Фото прогресса",
    tierLabel: "Золото",
    tier: "gold",
    title: "Хроника прогресса",
    description: "30 фото прогресса",
    threshold: "30",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/86-hronika-progressa.png",
  },
  {
    collectionId: "TRANS-PHOTOS",
    levelId: "TRANS-PHOTOS-MASTER",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Фото прогресса",
    tierLabel: "Мастер",
    tier: "master",
    title: "Документальный фильм",
    description: "60 фото прогресса",
    threshold: "60",
    score: 100,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/87-dokumentalnyi-film.png",
  },
  {
    collectionId: "TRANS-MEASUREMENTS",
    levelId: "TRANS-MEASUREMENTS-BRONZE",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Замеры",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Первый контроль",
    description: "5 замеров",
    threshold: "5",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/88-pervyi-kontrol.png",
  },
  {
    collectionId: "TRANS-MEASUREMENTS",
    levelId: "TRANS-MEASUREMENTS-SILVER",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Замеры",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Следую плану",
    description: "20 замеров",
    threshold: "20",
    score: 25,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/89-sleduyu-planu.png",
  },
  {
    collectionId: "TRANS-MEASUREMENTS",
    levelId: "TRANS-MEASUREMENTS-GOLD",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Замеры",
    tierLabel: "Золото",
    tier: "gold",
    title: "Всё под контролем",
    description: "50 замеров",
    threshold: "50",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/90-vse-pod-kontrolem.png",
  },
  {
    collectionId: "TRANS-MEASUREMENTS",
    levelId: "TRANS-MEASUREMENTS-MASTER",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Замеры",
    tierLabel: "Мастер",
    tier: "master",
    title: "Точный контроль",
    description: "60 замеров",
    threshold: "60",
    score: 100,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/91-tochnyi-kontrol.png",
  },
  {
    collectionId: "TRANS-NEW-GOAL",
    levelId: "TRANS-NEW-GOAL-BRONZE",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Новая цель",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Следующая вершина",
    description: "Поставить новую цель после первой",
    threshold: "1",
    score: 10,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/92-sleduyushchaya-vershina.png",
  },
  {
    collectionId: "TRANS-NEW-GOAL",
    levelId: "TRANS-NEW-GOAL-SILVER",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Новая цель",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Не останавливаюсь",
    description: "Вторая достигнутая цель",
    threshold: "2",
    score: 25,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/93-ne-ostanavlivayus.png",
  },
  {
    collectionId: "TRANS-NEW-GOAL",
    levelId: "TRANS-NEW-GOAL-GOLD",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Новая цель",
    tierLabel: "Золото",
    tier: "gold",
    title: "Путь продолжается",
    description: "Третья достигнутая цель",
    threshold: "3",
    score: 50,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/94-put-prodolzhaetsya.png",
  },
  {
    collectionId: "TRANS-NEW-GOAL",
    levelId: "TRANS-NEW-GOAL-MASTER",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Новая цель",
    tierLabel: "Мастер",
    tier: "master",
    title: "Бесконечный прогресс",
    description: "Пять достигнутых целей",
    threshold: "5",
    score: 100,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/95-beskonechnyi-progress.png",
  },
  {
    collectionId: "TRANS-SECRETS",
    levelId: "TRANS-SECRET-BEFORE-AFTER",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Секреты трансформации",
    tierLabel: "Секретное",
    tier: "secret",
    title: "До и После",
    description: "Сделать первое сравнение фотографий",
    threshold: "1",
    score: 25,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/96-do-i-posle.png",
  },
  {
    collectionId: "TRANS-SECRETS",
    levelId: "TRANS-SECRET-NOT-RECOGNIZE",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Секреты трансформации",
    tierLabel: "Секретное",
    tier: "secret",
    title: "Не узнаю себя",
    description: "Разница между первым и последним фото больше года",
    threshold: "1 год",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/97-ne-uznayu-sebya.png",
  },
  {
    collectionId: "TRANS-SECRETS",
    levelId: "TRANS-SECRET-SIZE-DOWN",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Секреты трансформации",
    tierLabel: "Секретное",
    tier: "secret",
    title: "Минус размер",
    description: "Существенное уменьшение объёмов",
    threshold: "событие",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/98-minus-razmer.png",
  },
  {
    collectionId: "TRANS-SECRETS",
    levelId: "TRANS-SECRET-EXACT-GOAL",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Секреты трансформации",
    tierLabel: "Секретное",
    tier: "secret",
    title: "Попал в десятку",
    description: "Достиг цели с точностью ±0,5 кг",
    threshold: "±0,5 кг",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/99-popal-v-desyatku.png",
  },
  {
    collectionId: "TRANS-SECRETS",
    levelId: "TRANS-SECRET-COMEBACK",
    categoryLabel: "Трансформация",
    category: "progress",
    collection: "Секреты трансформации",
    tierLabel: "Секретное",
    tier: "secret",
    title: "Обратная трансформация",
    description: "После отката снова достиг цели",
    threshold: "событие",
    score: 100,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/100-obratnaya-transformatsiya.png",
  },
  {
    collectionId: "FORM-CARDIO",
    levelId: "FORM-CARDIO-BRONZE",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Кардио",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Разгон",
    description: "10 кардиотренировок",
    threshold: "10",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/101-razgon.png",
  },
  {
    collectionId: "FORM-CARDIO",
    levelId: "FORM-CARDIO-SILVER",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Кардио",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Второе дыхание",
    description: "30 кардиотренировок",
    threshold: "30",
    score: 25,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/102-vtoroe-dyhanie.png",
  },
  {
    collectionId: "FORM-CARDIO",
    levelId: "FORM-CARDIO-GOLD",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Кардио",
    tierLabel: "Золото",
    tier: "gold",
    title: "Кардиомашина",
    description: "75 кардиотренировок",
    threshold: "75",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/103-kardiomashina.png",
  },
  {
    collectionId: "FORM-CARDIO",
    levelId: "FORM-CARDIO-MASTER",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Кардио",
    tierLabel: "Мастер",
    tier: "master",
    title: "Железные лёгкие",
    description: "110 кардиотренировок",
    threshold: "110",
    score: 100,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/104-zheleznye-legkie.png",
  },
  {
    collectionId: "FORM-RECOVERY",
    levelId: "FORM-RECOVERY-BRONZE",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Восстановление",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Умею отдыхать",
    description: "10 восстановительных тренировок",
    threshold: "10",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/105-umeyu-otdyhat.png",
  },
  {
    collectionId: "FORM-RECOVERY",
    levelId: "FORM-RECOVERY-SILVER",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Восстановление",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Восстановление в ритме",
    description: "30 восстановительных тренировок",
    threshold: "30",
    score: 25,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/106-vosstanovlenie-v-ritme.png",
  },
  {
    collectionId: "FORM-RECOVERY",
    levelId: "FORM-RECOVERY-GOLD",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Восстановление",
    tierLabel: "Золото",
    tier: "gold",
    title: "Восстановление — сила",
    description: "75 восстановительных тренировок",
    threshold: "75",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/107-vosstanovlenie-sila.png",
  },
  {
    collectionId: "FORM-RECOVERY",
    levelId: "FORM-RECOVERY-MASTER",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Восстановление",
    tierLabel: "Мастер",
    tier: "master",
    title: "Никогда не перегорю",
    description: "110 восстановительных тренировок",
    threshold: "110",
    score: 100,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/108-nikogda-ne-peregoryu.png",
  },
  {
    collectionId: "FORM-WELLBEING",
    levelId: "FORM-WELLBEING-BRONZE",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Самочувствие",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "На связи с телом",
    description: "20 заполненных чек-инов",
    threshold: "20",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/109-na-svyazi-s-telom.png",
  },
  {
    collectionId: "FORM-WELLBEING",
    levelId: "FORM-WELLBEING-SILVER",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Самочувствие",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Осознанный спортсмен",
    description: "50 заполненных чек-инов",
    threshold: "50",
    score: 25,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/110-osoznannyi-sportsmen.png",
  },
  {
    collectionId: "FORM-WELLBEING",
    levelId: "FORM-WELLBEING-GOLD",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Самочувствие",
    tierLabel: "Золото",
    tier: "gold",
    title: "Знаю своё тело",
    description: "100 заполненных чек-инов",
    threshold: "100",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/111-znayu-svoe-telo.png",
  },
  {
    collectionId: "FORM-WELLBEING",
    levelId: "FORM-WELLBEING-MASTER",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Самочувствие",
    tierLabel: "Мастер",
    tier: "master",
    title: "Биохакер",
    description: "250 заполненных чек-инов",
    threshold: "250",
    score: 100,
    version: "Later",
    catalogStatus: "Спорно",
    rarity: "epic",
    assetSrc: "/achievements/v1/112-biohaker.png",
  },
  {
    collectionId: "FORM-BALANCE",
    levelId: "FORM-BALANCE-BRONZE",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Баланс",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Баланс",
    description: "Выполнены все типы тренировок недели",
    threshold: "1 неделя",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/113-balans.png",
  },
  {
    collectionId: "FORM-BALANCE",
    levelId: "FORM-BALANCE-SILVER",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Баланс",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Гармония",
    description: "Месяц сбалансированного процесса",
    threshold: "1 месяц",
    score: 25,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/114-garmoniya.png",
  },
  {
    collectionId: "FORM-BALANCE",
    levelId: "FORM-BALANCE-GOLD",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Баланс",
    tierLabel: "Золото",
    tier: "gold",
    title: "Система",
    description: "Полгода сбалансированного процесса",
    threshold: "6 месяцев",
    score: 50,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/115-sistema.png",
  },
  {
    collectionId: "FORM-BALANCE",
    levelId: "FORM-BALANCE-MASTER",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Баланс",
    tierLabel: "Мастер",
    tier: "master",
    title: "Совершенный баланс",
    description: "Год сбалансированного процесса",
    threshold: "1 год",
    score: 100,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/116-sovershennyi-balans.png",
  },
  {
    collectionId: "FORM-DELOAD",
    levelId: "FORM-DELOAD-BRONZE",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Recovery Week",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Умею разгружаться",
    description: "Первая выполненная восстановительная неделя",
    threshold: "1",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/117-umeyu-razgruzhatsya.png",
  },
  {
    collectionId: "FORM-DELOAD",
    levelId: "FORM-DELOAD-SILVER",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Recovery Week",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Без перегрузок",
    description: "5 выполненных восстановительных недель",
    threshold: "5",
    score: 25,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/118-bez-peregruzok.png",
  },
  {
    collectionId: "FORM-DELOAD",
    levelId: "FORM-DELOAD-GOLD",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Recovery Week",
    tierLabel: "Золото",
    tier: "gold",
    title: "Восстановление — часть прогресса",
    description: "15 выполненных восстановительных недель",
    threshold: "15",
    score: 50,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/119-vosstanovlenie-chast-progressa.png",
  },
  {
    collectionId: "FORM-DELOAD",
    levelId: "FORM-DELOAD-MASTER",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Recovery Week",
    tierLabel: "Мастер",
    tier: "master",
    title: "Мастер восстановления",
    description: "50 выполненных восстановительных недель",
    threshold: "50",
    score: 100,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/120-master-vosstanovleniya.png",
  },
  {
    collectionId: "FORM-SLEEP",
    levelId: "FORM-SLEEP-BRONZE",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Сон",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Сон важнее всего",
    description: "Неделю подряд высокий рейтинг сна",
    threshold: "7 дней",
    score: 10,
    version: "Later",
    catalogStatus: "Отложено",
    rarity: "base",
    assetSrc: "/achievements/v1/121-son-vazhnee-vsego.png",
  },
  {
    collectionId: "FORM-HRV",
    levelId: "FORM-HRV-BRONZE",
    categoryLabel: "Форма",
    category: "progress",
    collection: "HRV",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Восстановился",
    description: "Стабильный HRV в течение периода",
    threshold: "период",
    score: 10,
    version: "Later",
    catalogStatus: "Отложено",
    rarity: "base",
    assetSrc: "/achievements/v1/122-vosstanovilsya.png",
  },
  {
    collectionId: "FORM-MOBILITY",
    levelId: "FORM-MOBILITY-SILVER",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Мобильность",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Свобода движения",
    description: "30 тренировок мобильности",
    threshold: "30",
    score: 25,
    version: "Later",
    catalogStatus: "Отложено",
    rarity: "rare",
    assetSrc: "/achievements/v1/123-svoboda-dvizheniya.png",
  },
  {
    collectionId: "FORM-FLEXIBILITY",
    levelId: "FORM-FLEXIBILITY-SILVER",
    categoryLabel: "Форма",
    category: "progress",
    collection: "Гибкость",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Гибче вчера",
    description: "30 тренировок растяжки",
    threshold: "30",
    score: 25,
    version: "Later",
    catalogStatus: "Отложено",
    rarity: "rare",
    assetSrc: "/achievements/v1/124-gibche-vchera.png",
  },
  {
    collectionId: "CLUB-LOYALTY",
    levelId: "CLUB-LOYALTY-BRONZE",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Верность клубу",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Первый месяц",
    description: "30 дней с тренером",
    threshold: "30 дней",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/125-pervyi-mesyats.png",
  },
  {
    collectionId: "CLUB-LOYALTY",
    levelId: "CLUB-LOYALTY-SILVER",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Верность клубу",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Уже свой",
    description: "180 дней с тренером",
    threshold: "180 дней",
    score: 25,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/126-uzhe-svoy.png",
  },
  {
    collectionId: "CLUB-LOYALTY",
    levelId: "CLUB-LOYALTY-GOLD",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Верность клубу",
    tierLabel: "Золото",
    tier: "gold",
    title: "Старожил",
    description: "250 дней с тренером",
    threshold: "250 дней",
    score: 50,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/127-starozhil.png",
  },
  {
    collectionId: "CLUB-LOYALTY",
    levelId: "CLUB-LOYALTY-MASTER",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Верность клубу",
    tierLabel: "Мастер",
    tier: "master",
    title: "Ветеран клуба",
    description: "365 дней с тренером",
    threshold: "365 дней",
    score: 100,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/128-veteran-kluba.png",
  },
  {
    collectionId: "CLUB-EXPLORE",
    levelId: "CLUB-EXPLORE-BRONZE",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Исследователь платформы",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "Любопытный",
    description: "Посетить все основные разделы приложения",
    threshold: "все разделы",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/129-lyubopytnyi.png",
  },
  {
    collectionId: "CLUB-EXPLORE",
    levelId: "CLUB-EXPLORE-SILVER",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Исследователь платформы",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Исследователь",
    description: "Использовать все ключевые функции хотя бы один раз",
    threshold: "все функции",
    score: 25,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/130-issledovatel.png",
  },
  {
    collectionId: "CLUB-EXPLORE",
    levelId: "CLUB-EXPLORE-GOLD",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Исследователь платформы",
    tierLabel: "Золото",
    tier: "gold",
    title: "Освоил систему",
    description: "Использовать все разделы повторно в течение месяца",
    threshold: "1 месяц",
    score: 50,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/131-osvoil-sistemu.png",
  },
  {
    collectionId: "CLUB-EXPLORE",
    levelId: "CLUB-EXPLORE-MASTER",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Исследователь платформы",
    tierLabel: "Мастер",
    tier: "master",
    title: "Мастер платформы",
    description: "Активно пользоваться всеми возможностями 180 дней",
    threshold: "180 дней",
    score: 100,
    version: "Later",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/132-master-platformy.png",
  },
  {
    collectionId: "CLUB-ACTIVE",
    levelId: "CLUB-ACTIVE-BRONZE",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Постоянный участник",
    tierLabel: "Бронза",
    tier: "bronze",
    title: "В клубе",
    description: "30 активных дней",
    threshold: "30 дней",
    score: 10,
    version: "MVP",
    catalogStatus: "К согласованию",
    rarity: "base",
    assetSrc: "/achievements/v1/133-v-klube.png",
  },
  {
    collectionId: "CLUB-ACTIVE",
    levelId: "CLUB-ACTIVE-SILVER",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Постоянный участник",
    tierLabel: "Серебро",
    tier: "silver",
    title: "Привычка",
    description: "100 активных дней",
    threshold: "100 дней",
    score: 25,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "rare",
    assetSrc: "/achievements/v1/134-privychka.png",
  },
  {
    collectionId: "CLUB-ACTIVE",
    levelId: "CLUB-ACTIVE-GOLD",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Постоянный участник",
    tierLabel: "Золото",
    tier: "gold",
    title: "Каждый день рядом",
    description: "250 активных дней",
    threshold: "250 дней",
    score: 50,
    version: "Later",
    catalogStatus: "Спорно",
    rarity: "rare",
    assetSrc: "/achievements/v1/135-kazhdyi-den-ryadom.png",
  },
  {
    collectionId: "CLUB-ACTIVE",
    levelId: "CLUB-ACTIVE-MASTER",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Постоянный участник",
    tierLabel: "Мастер",
    tier: "master",
    title: "Часть жизни",
    description: "365 активных дней",
    threshold: "365 дней",
    score: 100,
    version: "Later",
    catalogStatus: "Спорно",
    rarity: "epic",
    assetSrc: "/achievements/v1/136-chast-zhizni.png",
  },
  {
    collectionId: "CLUB-DATES",
    levelId: "CLUB-DATE-BIRTHDAY",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Особые даты",
    tierLabel: "Секретное",
    tier: "secret",
    title: "День рождения в зале",
    description: "Завершить тренировку в день рождения",
    threshold: "дата рождения",
    score: 25,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/137-den-rozhdeniya-v-zale.png",
  },
  {
    collectionId: "CLUB-DATES",
    levelId: "CLUB-DATE-NEW-YEAR",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Особые даты",
    tierLabel: "Секретное",
    tier: "secret",
    title: "Новый год без пропуска",
    description: "Провести тренировку 31 декабря или 1 января",
    threshold: "31.12 / 01.01",
    score: 25,
    version: "Later",
    catalogStatus: "Спорно",
    rarity: "epic",
    assetSrc: "/achievements/v1/138-novyi-god-bez-propuska.png",
  },
  {
    collectionId: "CLUB-DATES",
    levelId: "CLUB-DATE-ANNIVERSARY",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Особые даты",
    tierLabel: "Секретное",
    tier: "secret",
    title: "Годовщина",
    description: "Провести тренировку в годовщину регистрации",
    threshold: "годовщина",
    score: 25,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/139-godovshchina.png",
  },
  {
    collectionId: "CLUB-DATES",
    levelId: "CLUB-DATE-HOLIDAYS",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Особые даты",
    tierLabel: "Секретное",
    tier: "secret",
    title: "Праздники вместе",
    description: "Собрать все праздничные достижения",
    threshold: "набор дат",
    score: 100,
    version: "Later",
    catalogStatus: "Спорно",
    rarity: "epic",
    assetSrc: "/achievements/v1/140-prazdniki-vmeste.png",
  },
  {
    collectionId: "HONOR-TROPHIES",
    levelId: "HONOR-SUMMER-CHALLENGE",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Почётные трофеи",
    tierLabel: "Почётное",
    tier: "secret",
    title: "Участник Summer Challenge",
    description: "Завершить летний марафон",
    threshold: "событие",
    score: 0,
    version: "Later",
    catalogStatus: "Отложено",
    rarity: "epic",
    assetSrc: "/achievements/v1/141-uchastnik-summer-challenge.png",
  },
  {
    collectionId: "HONOR-TROPHIES",
    levelId: "HONOR-WINTER-CHALLENGE",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Почётные трофеи",
    tierLabel: "Почётное",
    tier: "secret",
    title: "Winter Challenge",
    description: "Завершить зимний марафон",
    threshold: "событие",
    score: 0,
    version: "Later",
    catalogStatus: "Отложено",
    rarity: "epic",
    assetSrc: "/achievements/v1/142-winter-challenge.png",
  },
  {
    collectionId: "HONOR-TROPHIES",
    levelId: "HONOR-BETA-TESTER",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Почётные трофеи",
    tierLabel: "Почётное",
    tier: "secret",
    title: "Beta Tester",
    description: "Использовать раннюю версию платформы",
    threshold: "событие",
    score: 0,
    version: "Later",
    catalogStatus: "Отложено",
    rarity: "epic",
    assetSrc: "/achievements/v1/143-beta-tester.png",
  },
  {
    collectionId: "HONOR-TROPHIES",
    levelId: "HONOR-FOUNDER",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Почётные трофеи",
    tierLabel: "Почётное",
    tier: "secret",
    title: "Основатель клуба",
    description: "Быть одним из первых пользователей сервиса",
    threshold: "событие",
    score: 0,
    version: "Later",
    catalogStatus: "Отложено",
    rarity: "epic",
    assetSrc: "/achievements/v1/144-osnovatel-kluba.png",
  },
  {
    collectionId: "HONOR-TROPHIES",
    levelId: "HONOR-FIRST-CLIENT",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Почётные трофеи",
    tierLabel: "Почётное",
    tier: "secret",
    title: "Первый клиент",
    description: "Первый клиент конкретного тренера",
    threshold: "событие",
    score: 0,
    version: "Later",
    catalogStatus: "Отложено",
    rarity: "epic",
    assetSrc: "/achievements/v1/145-pervyi-klient.png",
  },
  {
    collectionId: "COACH-LEGENDS",
    levelId: "COACH-LEGEND-FIRST-STUDENT",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Легенды тренера",
    tierLabel: "Секретное",
    tier: "secret",
    title: "Первый ученик",
    description: "Первый клиент тренера, завершивший программу",
    threshold: "событие",
    score: 50,
    version: "Later",
    catalogStatus: "Отложено",
    rarity: "epic",
    assetSrc: "/achievements/v1/146-pervyi-uchenik.png",
  },
  {
    collectionId: "COACH-LEGENDS",
    levelId: "COACH-LEGEND-3Y",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Легенды тренера",
    tierLabel: "Секретное",
    tier: "secret",
    title: "Вместе до конца",
    description: "Пройти с одним тренером более 3 лет",
    threshold: "3 года",
    score: 100,
    version: "Later",
    catalogStatus: "Отложено",
    rarity: "epic",
    assetSrc: "/achievements/v1/147-vmeste-do-kontsa.png",
  },
  {
    collectionId: "COACH-LEGENDS",
    levelId: "COACH-LEGEND-TANDEM",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Легенды тренера",
    tierLabel: "Секретное",
    tier: "secret",
    title: "Идеальный тандем",
    description: "100 тренировок подряд без переноса и без смены тренера",
    threshold: "100 тренировок",
    score: 100,
    version: "Later",
    catalogStatus: "Спорно",
    rarity: "epic",
    assetSrc: "/achievements/v1/148-idealnyi-tandem.png",
  },
  {
    collectionId: "COACH-LEGENDS",
    levelId: "COACH-LEGEND-MESSAGES",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Легенды тренера",
    tierLabel: "Секретное",
    tier: "secret",
    title: "Понимаем с полуслова",
    description: "Более 500 сообщений между тренером и клиентом",
    threshold: "500 сообщений",
    score: 50,
    version: "Later",
    catalogStatus: "Отложено",
    rarity: "epic",
    assetSrc: "/achievements/v1/149-ponimaem-s-poluslova.png",
  },
  {
    collectionId: "COACH-LEGENDS",
    levelId: "COACH-LEGEND-SUCCESS",
    categoryLabel: "Клуб",
    category: "community",
    collection: "Легенды тренера",
    tierLabel: "Секретное",
    tier: "secret",
    title: "История успеха",
    description: "Клиент достиг главной цели и завершил программу",
    threshold: "событие",
    score: 100,
    version: "V2",
    catalogStatus: "К согласованию",
    rarity: "epic",
    assetSrc: "/achievements/v1/150-istoriya-uspeha.png",
  },
];

export function buildAchievementCatalogForAthlete(athleteAchievements: AthleteAchievement[]): AthleteAchievement[] {
  const athleteAchievementByLevel = new Map(
    athleteAchievements.map((achievement) => [achievement.levelId ?? achievement.id, achievement])
  );

  return achievementCatalog.map((catalogItem) => {
    const athleteAchievement = athleteAchievementByLevel.get(catalogItem.levelId);

    return {
      id: catalogItem.levelId,
      levelId: catalogItem.levelId,
      collectionId: catalogItem.collectionId,
      collection: catalogItem.collection,
      title: catalogItem.title,
      description: catalogItem.description,
      assetSrc: catalogItem.assetSrc,
      category: catalogItem.category,
      status: athleteAchievement?.status ?? "locked",
      rarity: athleteAchievement?.rarity ?? catalogItem.rarity,
      tier: catalogItem.tier,
      score: catalogItem.score,
      unlockedAt: athleteAchievement?.unlockedAt,
      progress: athleteAchievement?.progress,
    };
  });
}
