import {
  Camera,
  CheckCircle2,
  ClipboardCheck,
  Dumbbell,
  MessageSquareText,
  Ruler,
  Weight,
} from "lucide-react";

import type { AthleteProfile } from "./types";

export const athleteProfiles: AthleteProfile[] = [
  {
    id: "artem-smirnov",
    name: "Артём Смирнов",
    initials: "АС",
    goal: "Набор массы",
    about: "Работает в офисе, тренируется вечером. Хочет набрать мышечную массу без резкого роста талии и сохранить плечи здоровыми.",
    trainingExperience: "3 года регулярных тренировок, уверенно работает со свободными весами",
    equipment: [
      { id: "gym", label: "Полный зал", availability: "available" },
      { id: "barbell", label: "Штанга и стойки", availability: "available" },
      { id: "machines", label: "Блочные тренажёры", availability: "available" },
      { id: "cardio", label: "Кардио-зона", availability: "limited" },
    ],
    limitations: [
      { id: "shoulder", label: "Правое плечо", detail: "Иногда тянет в разведениях и тяжёлом жиме после высокого RPE.", severity: "medium" },
      { id: "sleep", label: "Сон", detail: "В рабочие дни может проседать до 6–7 часов.", severity: "low" },
    ],
    preferredTrainingDays: ["Понедельник", "Среда", "Пятница", "Воскресенье"],
    currentProgram: {
      id: "mass-8-week",
      name: "Набор массы · 8 недель",
      phase: "Основной силовой блок",
      week: 4,
      totalWeeks: 8,
      startedAt: "2026-05-25",
      endsAt: "2026-07-19",
      status: "active",
    },
    adherence: {
      workouts: 91,
      checkIns: 86,
      measurements: 78,
      overall: 88,
      label: "Стабильный ритм",
    },
    reputation: {
      score: 2840,
      rankId: "ATHLETE_II",
      progress: 84,
    },
    membership: {
      status: "active",
      source: "program_purchase",
      purchaseName: "Премиальное ведение · 8 недель",
      purchaseDate: "2026-05-20",
      subscriptionEndDate: "2026-07-20",
      accessStatus: "enabled",
      addedAt: "2026-05-20",
    },
    coachNotes: [
      {
        id: "note-1",
        title: "Следить за плечом",
        body: "После тяжёлого жима не повышать объём разведений. Лучше оставить технику и темп как главный фокус.",
        createdAt: "2026-06-20",
        pinned: true,
      },
      {
        id: "note-2",
        title: "Хорошо реагирует на малые прибавки",
        body: "Лучше +2.5 кг или +1 повтор, чем резкий скачок веса.",
        createdAt: "2026-06-14",
      },
    ],
    calendarEvents: [
      { id: "cal-1", type: "review", title: "Разбор Дня жима", date: "2026-06-22", time: "18:00", status: "waiting", detail: "Жим ниже плана на 2 повтора, RPE 9/10." },
      { id: "cal-2", type: "workout", title: "День тяги", date: "2026-06-23", time: "19:30", status: "planned", detail: "Следующий тренировочный день после разбора." },
      { id: "cal-3", type: "check_in", title: "Недельный чек-ин", date: "2026-06-25", status: "planned", detail: "Сон, энергия, аппетит, комментарий по плечу." },
      { id: "cal-4", type: "measurements", title: "Замеры и фото", date: "2026-06-29", status: "planned", detail: "Обновить объёмы и фото прогресса." },
      { id: "cal-5", type: "subscription", title: "Продление ведения", date: "2026-07-20", status: "risk", detail: "Заканчивается текущий период премиального ведения." },
    ],
    analyticsCards: [
      { id: "analytics-1", label: "Adherence", value: "88%", detail: "Тренировки и чек-ины держатся стабильно.", tone: "good" },
      { id: "analytics-2", label: "Силовой тренд", value: "+6%", detail: "Лучше всего растёт тяговой блок.", tone: "good" },
      { id: "analytics-3", label: "Усталость", value: "выше нормы", detail: "После дня жима стоит снизить давление на плечо.", tone: "warning" },
      { id: "analytics-4", label: "Риск недели", value: "плечо", detail: "Не повышать объём жимовых движений без разбора.", tone: "risk" },
    ],
    bestResults: [
      { id: "best-1", exercise: "Жим лёжа", value: "82.5×5", date: "Неделя 3", delta: "+2.5 кг", tone: "good" },
      { id: "best-2", exercise: "Становая тяга", value: "125×3", date: "Неделя 2", delta: "+5 кг", tone: "good" },
      { id: "best-3", exercise: "Тяга блока", value: "70×8", date: "Сегодня", delta: "личный рекорд", tone: "good" },
      { id: "best-4", exercise: "Присед", value: "105×3", date: "Неделя 3", delta: "стабильно", tone: "muted" },
    ],
    activeTitleId: "TITLE-STRENGTH",
    titles: [
      {
        id: "TITLE-DISCIPLINE",
        name: "Железная дисциплина",
        category: "discipline",
        description: "Закрывает ключевые коллекции дисциплины и держит тренировочный ритм.",
        asset: "/titles/v1/151-zheleznaya-distsiplina.png",
        unlockedAt: "Неделя 4",
        isUnlocked: true,
      },
      {
        id: "TITLE-STRENGTH",
        name: "Повелитель силы",
        category: "strength",
        description: "Большой титул за ключевые силовые кубки.",
        asset: "/titles/v1/152-povelitel-sily.png",
        unlockedAt: "Сегодня",
        isUnlocked: true,
      },
      {
        id: "TITLE-TRANSFORMATION",
        name: "Архитектор тела",
        category: "transformation",
        description: "Завершить главную цель и пройти полный цикл изменений.",
        asset: "/titles/v1/153-arhitektor-tela.png",
        isUnlocked: false,
      },
      {
        id: "TITLE-FORM",
        name: "Гармония тела",
        category: "form",
        description: "Закрыть ключевые достижения формы, восстановления и самочувствия.",
        asset: "/titles/v1/154-garmoniya-tela.png",
        isUnlocked: false,
      },
      {
        id: "TITLE-CLUB",
        name: "Душа клуба",
        category: "club",
        description: "Закрыть ключевые достижения клуба и провести минимум год в системе.",
        asset: "/titles/v1/155-dusha-kluba.png",
        isUnlocked: false,
      },
      {
        id: "TITLE-MACHINE",
        name: "Машина",
        category: "special",
        description: "500 тренировок, длинная серия и минимум два года в системе.",
        asset: "/titles/v1/156-mashina.png",
        isUnlocked: false,
      },
      {
        id: "TITLE-UNBREAKABLE",
        name: "Несокрушимый",
        category: "special",
        description: "Пройти трансформацию, вернуться после паузы и снова достигнуть цели.",
        asset: "/titles/v1/157-nesokrushimyi.png",
        isUnlocked: false,
      },
      {
        id: "TITLE-IRON-MAN",
        name: "Железный человек",
        category: "special",
        description: "Получить титулы Повелитель силы, Железная дисциплина и Гармония тела.",
        asset: "/titles/v1/158-zheleznyi-chelovek.png",
        isUnlocked: false,
      },
      {
        id: "TITLE-CLUB-LEGEND",
        name: "Легенда клуба",
        category: "special",
        description: "Получить 80% всех достижений платформы.",
        asset: "/titles/v1/159-legenda-kluba.png",
        isUnlocked: false,
      },
      {
        id: "TITLE-ABSOLUTE",
        name: "Абсолют",
        category: "special",
        description: "Получить все титулы, кубки, медали и секретные достижения.",
        asset: "/titles/v1/160-absolut.png",
        isUnlocked: false,
      },
    ],
    achievements: [
      {
        id: "START-FIRST-CYCLE-BRONZE",
        levelId: "START-FIRST-CYCLE-BRONZE",
        collectionId: "START-FIRST-CYCLE",
        collection: "Первый микроцикл",
        title: "Первый микроцикл",
        description: "Завершил первый тренировочный микроцикл.",
        assetSrc: "/achievements/v1/06-pervyi-mikrotsikl.png",
        category: "training",
        status: "unlocked",
        rarity: "base",
        tier: "bronze",
        score: 10,
        unlockedAt: "Неделя 1",
      },
      {
        id: "DISC-STREAK-BRONZE",
        levelId: "DISC-STREAK-BRONZE",
        collectionId: "DISC-STREAK",
        collection: "Серия тренировок",
        title: "В ритме",
        description: "7 тренировок подряд без провала ритма.",
        assetSrc: "/achievements/v1/07-v-ritme.png",
        category: "consistency",
        status: "unlocked",
        rarity: "rare",
        tier: "bronze",
        score: 10,
        unlockedAt: "Неделя 3",
      },
      {
        id: "STR-SECRET-3PRS",
        levelId: "STR-SECRET-3PRS",
        collectionId: "STR-SECRETS",
        collection: "Секретные силовые",
        title: "День рекордов",
        description: "3 личных рекорда за одну тренировку.",
        assetSrc: "/achievements/v1/70-den-rekordov.png",
        category: "strength",
        status: "unlocked",
        rarity: "epic",
        tier: "secret",
        score: 50,
        unlockedAt: "Сегодня",
      },
      {
        id: "DISC-PHOTOS-RHYTHM-BRONZE",
        levelId: "DISC-PHOTOS-RHYTHM-BRONZE",
        collectionId: "DISC-PHOTOS-RHYTHM",
        collection: "Ритм фотоотчётов",
        title: "Фото по плану",
        description: "4 недели с фотоотчётами по расписанию.",
        assetSrc: "/achievements/v1/27-foto-po-planu.png",
        category: "progress",
        status: "in_progress",
        rarity: "base",
        tier: "bronze",
        score: 10,
        progress: { current: 3, target: 4, label: "3 из 4 отчётов" },
      },
      {
        id: "STR-BENCH-BRONZE",
        levelId: "STR-BENCH-BRONZE",
        collectionId: "STR-BENCH",
        collection: "Жим лёжа",
        title: "Железная сотня",
        description: "Жим лёжа 100 кг.",
        assetSrc: "/achievements/v1/43-zheleznaya-sotnya.png",
        category: "strength",
        status: "in_progress",
        rarity: "epic",
        tier: "cup",
        score: 50,
        progress: { current: 82.5, target: 100, label: "82.5 из 100 кг" },
      },
      {
        id: "DISC-CHECKINS-SILVER",
        levelId: "DISC-CHECKINS-SILVER",
        collectionId: "DISC-CHECKINS",
        collection: "Чек-ины",
        title: "Ответственный",
        description: "30 чек-инов за период сопровождения.",
        assetSrc: "/achievements/v1/20-otvetstvennyi.png",
        category: "community",
        status: "in_progress",
        rarity: "rare",
        tier: "silver",
        score: 25,
        progress: { current: 22, target: 30, label: "22 из 30 чек-инов" },
      },
      {
        id: "TRANS-MASS-SILVER",
        levelId: "TRANS-MASS-SILVER",
        collectionId: "TRANS-MASS",
        collection: "Набор массы",
        title: "Уже заметно",
        description: "Выполнено 50% цели по набору массы.",
        assetSrc: "/achievements/v1/81-uzhe-zametno.png",
        category: "progress",
        status: "in_progress",
        rarity: "rare",
        tier: "silver",
        score: 25,
        progress: { current: 44, target: 50, label: "44% из 50%" },
      },
    ],
    profilePosts: [
      {
        id: "feed-1",
        type: "post",
        author: "client",
        title: "Тяжёлый жим, но без провала",
        body: "Сегодня последний подход дался тяжелее обычного. Вес держу, но плечо в разведениях лучше не грузить.",
        time: "Сегодня · 2 часа назад",
        meta: "Пост клиента",
        tone: "warning",
        stats: { reactions: 3, comments: 1 },
      },
      {
        id: "feed-2",
        type: "achievement",
        author: "system",
        title: "Открыто достижение «В ритме»",
        body: "Артём держит тренировочный график три недели подряд.",
        time: "Неделя 3",
        meta: "Достижение",
        tone: "good",
        stats: { reactions: 5 },
      },
      {
        id: "feed-3",
        type: "photo",
        author: "client",
        title: "Фотоотчёт недели",
        body: "Добавлены фронт, профиль и спина. Видно, что талия остаётся стабильной при росте веса.",
        time: "Неделя 4",
        meta: "Фото прогресса",
        tone: "muted",
        stats: { comments: 2 },
      },
      {
        id: "feed-4",
        type: "workout",
        author: "system",
        title: "Низ тела разобран",
        body: "Тренировка закрыта без правок. Следующий шаг по нижней части тела можно оставить прежним.",
        time: "2 дня назад",
        meta: "Тренировка",
        tone: "good",
      },
      {
        id: "feed-5",
        type: "check_in",
        author: "client",
        title: "Чек-ин: сон и энергия",
        body: "Сон 7/10, энергия 8/10. Аппетит высокий, питание без срывов.",
        time: "3 дня назад",
        meta: "Чек-ин",
        tone: "good",
        stats: { comments: 1 },
      },
    ],
    progressPhotos: [
      { id: "photo-front-w4", label: "Фронт", date: "Неделя 4", view: "front", status: "new" },
      { id: "photo-side-w4", label: "Профиль", date: "Неделя 4", view: "side", status: "new" },
      { id: "photo-back-w4", label: "Спина", date: "Неделя 4", view: "back", status: "reviewed" },
    ],
    management: {
      addedAt: "2026-05-20",
      source: "program_purchase",
      subscriptionStatus: "active",
      purchaseName: "Премиальное ведение · 8 недель",
      purchaseDate: "2026-05-20",
      subscriptionEndDate: "2026-07-20",
      nextPaymentDate: "2026-07-15",
      tariffName: "Premium coaching · 8 недель",
      tariffAmount: "94 000 ₽",
      accessStatus: "enabled",
      canMessage: true,
      canAccessWorkouts: true,
      canUploadProgress: true,
      inviteLink: "https://app.ai-strength.coach/join/artem-smirnov",
      purchasedPrograms: [
        {
          id: "purchase-current-program",
          title: "Набор массы · 8 недель",
          detail: "Основной силовой блок · неделя 4 из 8",
          status: "Активна",
        },
        {
          id: "purchase-exercise-library",
          title: "Библиотека упражнений",
          detail: "Доступ к технике, видео и заменам упражнений",
          status: "Включено",
        },
        {
          id: "purchase-progress-tools",
          title: "Фото и замеры",
          detail: "Прогресс-фото, вес, замеры тела и чек-ины",
          status: "Включено",
        },
      ],
      paymentHistory: [
        {
          id: "payment-current",
          date: "2026-05-20",
          title: "Премиальное ведение · 8 недель",
          amount: "94 000 ₽",
          status: "Оплачено",
          tone: "good",
        },
        {
          id: "payment-next",
          date: "2026-07-15",
          title: "Следующее продление ведения",
          amount: "94 000 ₽",
          status: "Ожидается",
          tone: "warning",
        },
        {
          id: "payment-start",
          date: "2026-05-20",
          title: "Стартовый пакет",
          amount: "0 ₽",
          status: "Включено",
          tone: "muted",
        },
      ],
      dangerActions: ["pause_access", "disable_access", "remove_client"],
    },
    currentWeight: "74.2 кг",
    targetWeight: "80 кг",
    status: "Ждёт разбора",
    lastActivity: "Завершил день жима 2 часа назад",
    phase: "Неделя 4 из 8",
    nextWorkout: "День тяги · завтра",
    lastWorkout: "День жима · нагрузка 9/10",
    openIssues: ["Жим лёжа ниже плана на 2 повтора", "Высокая нагрузка в последнем подходе", "Плечо тянуло в разведениях"],
    upcomingWorkouts: [
      { id: "w1", title: "День тяги", date: "Завтра", meta: "Спина + бицепс · 55 мин", status: "Готова к назначению", tone: "warning" },
      { id: "w2", title: "Низ тела", date: "Пятница", meta: "Присед + задняя цепь", status: "Запланирована", tone: "good" },
      { id: "w3", title: "Восстановление", date: "Воскресенье", meta: "Мобильность · 30 мин", status: "Лёгкий день", tone: "muted" },
    ],
    workoutHistory: [
      { id: "h1", title: "День жима", date: "Сегодня", meta: "72 мин · 18 подходов · 7420 кг", status: "Ждёт разбора", tone: "warning" },
      { id: "h2", title: "Низ тела", date: "2 дня назад", meta: "64 мин · 16 подходов", status: "Разобрано", tone: "good" },
      { id: "h3", title: "День тяги", date: "4 дня назад", meta: "58 мин · 15 подходов", status: "Разобрано", tone: "good" },
      { id: "h4", title: "Верх тела", date: "6 дней назад", meta: "61 мин · 17 подходов", status: "Разобрано", tone: "good" },
      { id: "h5", title: "Низ тела", date: "8 дней назад", meta: "67 мин · 18 подходов", status: "Разобрано", tone: "good" },
      { id: "h6", title: "День тяги", date: "10 дней назад", meta: "54 мин · 14 подходов", status: "Разобрано", tone: "muted" },
      { id: "h7", title: "Восстановление", date: "12 дней назад", meta: "31 мин · мобильность", status: "Завершено", tone: "muted" },
    ],
    previousLoads: [
      { exercise: "Жим лёжа", last: "80×6", best: "82.5×5", trend: "тяжело 2 тренировки", tone: "warning" },
      { exercise: "Становая тяга", last: "120×5", best: "125×3", trend: "ровно", tone: "muted" },
      { exercise: "Тяга блока", last: "70×8", best: "70×8", trend: "личный рекорд", tone: "good" },
      { exercise: "Присед", last: "100×5", best: "105×3", trend: "стабильно", tone: "good" },
      { exercise: "Жим гантелей", last: "32×8", best: "34×6", trend: "растёт", tone: "good" },
      { exercise: "Румынская тяга", last: "95×8", best: "100×6", trend: "ровно", tone: "muted" },
      { exercise: "Подтягивания", last: "+10×6", best: "+12.5×5", trend: "растёт", tone: "good" },
      { exercise: "Жим ногами", last: "160×10", best: "170×8", trend: "растёт", tone: "good" },
      { exercise: "Разведения", last: "12×12", best: "14×10", trend: "беречь плечо", tone: "warning" },
      { exercise: "Сгибания ног", last: "45×12", best: "50×10", trend: "стабильно", tone: "good" },
    ],
    progression: [
      { label: "Силовой индекс", value: "+6%", detail: "за последние 4 недели", tone: "good" },
      { label: "Выполнение", value: "91%", detail: "по тренировкам цикла", tone: "good" },
      { label: "Усталость", value: "выше нормы", detail: "после дня жима", tone: "warning" },
    ],
    measurements: [
      { label: "Грудь", value: "101 см", delta: "+2 см" },
      { label: "Талия", value: "82 см", delta: "0 см" },
      { label: "Бедро", value: "58 см", delta: "+1 см" },
      { label: "Плечо", value: "36 см", delta: "+1 см" },
    ],
    weightTrend: [72.8, 73.1, 73.4, 73.6, 73.8, 74.0, 74.2],
    exerciseTrends: [
      {
        id: "trend-bench",
        exercise: "Жим лёжа",
        description: "Расчётная сила по рабочим подходам.",
        values: [74, 75, 77, 78, 80, 81, 82.5],
        unit: "кг",
        start: "74 кг",
        current: "82.5 кг",
        increase: "+11%",
        bestSet: "82.5 кг × 5",
        tone: "warning",
      },
      {
        id: "trend-deadlift",
        exercise: "Становая тяга",
        description: "Лучший тяжёлый подход в тяговом блоке.",
        values: [110, 112.5, 115, 117.5, 120, 122.5, 125],
        unit: "кг",
        start: "110 кг",
        current: "125 кг",
        increase: "+14%",
        bestSet: "125 кг × 3",
        tone: "good",
      },
      {
        id: "trend-squat",
        exercise: "Присед",
        description: "Силовой ориентир по нижней части тела.",
        values: [96, 98, 100, 100, 102.5, 105, 105],
        unit: "кг",
        start: "96 кг",
        current: "105 кг",
        increase: "+9%",
        bestSet: "105 кг × 3",
        tone: "good",
      },
      {
        id: "trend-pull",
        exercise: "Тяга блока",
        description: "Стабильный прогресс в тяговом объёме.",
        values: [60, 62.5, 65, 65, 67.5, 70, 70],
        unit: "кг",
        start: "60 кг",
        current: "70 кг",
        increase: "+17%",
        bestSet: "70 кг × 8",
        tone: "good",
      },
    ],
    photos: [
      { id: "p1", label: "Фронт", date: "Неделя 4" },
      { id: "p2", label: "Профиль", date: "Неделя 4" },
      { id: "p3", label: "Спина", date: "Неделя 4" },
    ],
    checkIns: [
      { id: "c1", label: "Сон", score: "7/10", detail: "хуже на 1 балл", tone: "warning" },
      { id: "c2", label: "Энергия", score: "8/10", detail: "нормально", tone: "good" },
      { id: "c3", label: "Аппетит", score: "9/10", detail: "высокий", tone: "good" },
    ],
    timeline: [
      { id: "t1", title: "День жима завершён", detail: "Жим лёжа 80×6 вместо 80×8, нагрузка 9/10.", time: "Сегодня · 2 часа назад", icon: Dumbbell, tone: "warning" },
      { id: "t2", title: "Комментарий клиента", detail: "Последний подход тяжёлый, в разведениях немного тянуло плечо.", time: "Сегодня", icon: MessageSquareText, tone: "risk" },
      { id: "t3", title: "Новая тренировка назначена", detail: "Низ тела был назначен после прошлого разбора.", time: "2 дня назад", icon: CheckCircle2, tone: "good" },
      { id: "t4", title: "Чек-ин отправлен", detail: "Сон 7/10, энергия 8/10, питание без срывов.", time: "3 дня назад", icon: ClipboardCheck, tone: "good" },
      { id: "t5", title: "Замеры обновлены", detail: "Грудь +2 см, бедро +1 см, талия без изменений.", time: "Неделя 4", icon: Ruler, tone: "good" },
      { id: "t6", title: "Вес обновлён", detail: "74.2 кг, тренд набора идёт ровно.", time: "Вчера", icon: Weight, tone: "good" },
      { id: "t7", title: "Фото прогресса", detail: "Добавлены фронт, профиль и спина.", time: "Неделя 4", icon: Camera, tone: "muted" },
    ],
  },
];

export function getAthleteProfile(clientId?: string): AthleteProfile {
  return athleteProfiles.find((profile) => profile.id === clientId) ?? athleteProfiles[0];
}
