import { ClipboardCheck, MessageCircle, Ruler, Scale } from "lucide-react";

import type { SecondaryAttentionItem, TeamActivityItem, TeamClient, TeamSummary } from "./types";

export const trainerHomeMockMode: "team" | "empty" | "calm" = "team";

export const trainerHomeClients: TeamClient[] = [
  {
    id: "artem-smirnov",
    name: "Артём Смирнов",
    initials: "АС",
    goal: "Набор массы",
    state: "waiting_review",
    stateLabel: "Ждёт разбора",
    progressTrend: "down",
    isOnline: true,
    priority: "high",
    lastActivity: "2 часа назад",
    nextWorkout: "День жима",
    issue: "Тренировка ждёт разбора",
    context: "Завершил День жима. Нагрузка 9/10, жим лёжа −2 повтора от плана.",
    primaryAction: "review",
  },
  {
    id: "olga-sokolova",
    name: "Ольга Соколова",
    initials: "ОС",
    goal: "Сила и осанка",
    state: "needs_adjustment",
    stateLabel: "Нужна корректировка",
    progressTrend: "down",
    isOnline: false,
    priority: "medium",
    lastActivity: "сегодня",
    nextWorkout: "День тяги",
    issue: "Нужна корректировка",
    context: "Пожаловалась на плечо после тяговой тренировки. Следующий тренировочный день лучше скорректировать.",
    primaryAction: "open_client",
  },
  {
    id: "egor-nikitin",
    name: "Егор Никитин",
    initials: "ЕН",
    goal: "Старт после паузы",
    state: "no_next_workout",
    stateLabel: "Нет следующей",
    progressTrend: "flat",
    isOnline: false,
    priority: "high",
    lastActivity: "вчера",
    issue: "Нет следующей тренировки",
    context: "Последняя тренировка завершена вчера. Новый тренировочный день не назначен.",
    primaryAction: "assign",
  },
  {
    id: "maria-volkova",
    name: "Мария Волкова",
    initials: "МВ",
    goal: "Сушка",
    state: "on_track",
    stateLabel: "По плану",
    progressTrend: "up",
    isOnline: true,
    priority: "low",
    lastActivity: "сегодня",
    nextWorkout: "Низ тела",
  },
  {
    id: "dmitry-korolev",
    name: "Дмитрий Королёв",
    initials: "ДК",
    goal: "Гипертрофия",
    state: "on_track",
    stateLabel: "По плану",
    progressTrend: "up",
    isOnline: true,
    priority: "low",
    lastActivity: "сегодня",
    nextWorkout: "Силовой верх",
  },
  {
    id: "sofia-andreeva",
    name: "София Андреева",
    initials: "СА",
    goal: "Тонус",
    state: "on_track",
    stateLabel: "По плану",
    progressTrend: "flat",
    isOnline: false,
    priority: "low",
    lastActivity: "вчера",
    nextWorkout: "Силовой пилатес",
  },
  {
    id: "nikita-ivanov",
    name: "Никита Иванов",
    initials: "НИ",
    goal: "Сила",
    state: "on_track",
    stateLabel: "По плану",
    progressTrend: "up",
    isOnline: true,
    priority: "low",
    lastActivity: "вчера",
    nextWorkout: "Фокус на присед",
  },
  {
    id: "anna-petrova",
    name: "Анна Петрова",
    initials: "АП",
    goal: "Рекомпозиция",
    state: "on_track",
    stateLabel: "По плану",
    progressTrend: "flat",
    isOnline: false,
    priority: "low",
    lastActivity: "2 дня назад",
    nextWorkout: "Полное тело",
  },
  {
    id: "kirill-orlov",
    name: "Кирилл Орлов",
    initials: "КО",
    goal: "Плечи и спина",
    state: "on_track",
    stateLabel: "По плану",
    progressTrend: "up",
    isOnline: false,
    priority: "low",
    lastActivity: "сегодня",
    nextWorkout: "Силовая тяга",
  },
  {
    id: "elena-kuznetsova",
    name: "Елена Кузнецова",
    initials: "ЕК",
    goal: "Выносливость",
    state: "on_track",
    stateLabel: "По плану",
    progressTrend: "flat",
    isOnline: false,
    priority: "low",
    lastActivity: "вчера",
    nextWorkout: "Кондиция",
  },
  {
    id: "roman-belov",
    name: "Роман Белов",
    initials: "РБ",
    goal: "Набор силы",
    state: "on_track",
    stateLabel: "По плану",
    progressTrend: "up",
    isOnline: false,
    priority: "low",
    lastActivity: "сегодня",
    nextWorkout: "День жима",
  },
  {
    id: "polina-gromova",
    name: "Полина Громова",
    initials: "ПГ",
    goal: "Минус 6 кг",
    state: "on_track",
    stateLabel: "По плану",
    progressTrend: "down",
    isOnline: false,
    priority: "low",
    lastActivity: "3 часа назад",
    nextWorkout: "Ягодицы",
  },
  {
    id: "ivan-melnikov",
    name: "Иван Мельников",
    initials: "ИМ",
    goal: "Марафон силы",
    state: "on_track",
    stateLabel: "По плану",
    progressTrend: "flat",
    isOnline: false,
    priority: "low",
    lastActivity: "вчера",
    nextWorkout: "День тяги",
  },
  {
    id: "alisa-zvereva",
    name: "Алиса Зверева",
    initials: "АЗ",
    goal: "Форма к лету",
    state: "on_track",
    stateLabel: "По плану",
    progressTrend: "up",
    isOnline: false,
    priority: "low",
    lastActivity: "сегодня",
    nextWorkout: "Лёгкий верх",
  },
  {
    id: "maxim-ustinov",
    name: "Максим Устинов",
    initials: "МУ",
    goal: "Пауэрлифтинг",
    state: "on_track",
    stateLabel: "По плану",
    progressTrend: "flat",
    isOnline: false,
    priority: "low",
    lastActivity: "вчера",
    nextWorkout: "Тяжёлый низ",
  },
  {
    id: "veronika-levina",
    name: "Вероника Левина",
    initials: "ВЛ",
    goal: "Здоровая спина",
    state: "on_track",
    stateLabel: "По плану",
    progressTrend: "up",
    isOnline: false,
    priority: "low",
    lastActivity: "2 дня назад",
    nextWorkout: "Мобильность",
  },
  {
    id: "pavel-sergeev",
    name: "Павел Сергеев",
    initials: "ПС",
    goal: "Жиросжигание",
    state: "on_track",
    stateLabel: "По плану",
    progressTrend: "flat",
    isOnline: true,
    priority: "low",
    lastActivity: "сегодня",
    nextWorkout: "Метаболическая",
  },
  {
    id: "yana-fedotova",
    name: "Яна Федотова",
    initials: "ЯФ",
    goal: "Тонус",
    state: "on_track",
    stateLabel: "По плану",
    progressTrend: "flat",
    isOnline: false,
    priority: "low",
    lastActivity: "вчера",
    nextWorkout: "Лёгкий низ",
  },
  {
    id: "timur-akimov",
    name: "Тимур Акимов",
    initials: "ТА",
    goal: "Мышечная масса",
    state: "on_track",
    stateLabel: "По плану",
    progressTrend: "up",
    isOnline: false,
    priority: "low",
    lastActivity: "сегодня",
    nextWorkout: "Объёмный жим",
  },
  {
    id: "irina-kozlova",
    name: "Ирина Козлова",
    initials: "ИК",
    goal: "Стабильный ритм",
    state: "on_track",
    stateLabel: "По плану",
    progressTrend: "flat",
    isOnline: true,
    priority: "low",
    lastActivity: "2 дня назад",
    nextWorkout: "Полное тело B",
  },
  {
    id: "leonid-savin",
    name: "Леонид Савин",
    initials: "ЛС",
    goal: "Возврат после отпуска",
    state: "on_track",
    stateLabel: "По плану",
    progressTrend: "up",
    isOnline: false,
    priority: "low",
    lastActivity: "вчера",
    nextWorkout: "Стартовая силовая",
  },
  {
    id: "ksenia-belyaeva",
    name: "Ксения Беляева",
    initials: "КБ",
    goal: "Пауза по работе",
    state: "inactive",
    stateLabel: "Пауза",
    progressTrend: "flat",
    isOnline: false,
    priority: "low",
    lastActivity: "9 дней назад",
    issue: "Тренировка не начата",
    context: "Запланированная тренировка пропущена. Нужен ручной контакт тренера.",
    primaryAction: "message",
  },
  {
    id: "vadim-larin",
    name: "Вадим Ларин",
    initials: "ВЛ",
    goal: "Командировка",
    state: "inactive",
    stateLabel: "Пауза",
    progressTrend: "flat",
    isOnline: false,
    priority: "low",
    lastActivity: "12 дней назад",
  },
  {
    id: "natalia-ershova",
    name: "Наталья Ершова",
    initials: "НЕ",
    goal: "Восстановление",
    state: "inactive",
    stateLabel: "Пауза",
    progressTrend: "flat",
    isOnline: false,
    priority: "low",
    lastActivity: "2 недели назад",
  },
];

export const teamActivityItems: TeamActivityItem[] = [
  {
    id: "activity-1",
    clientId: "artem-smirnov",
    clientName: "Артём Смирнов",
    type: "completed_workout",
    title: "Артём завершил День жима",
    description: "18 подходов, нагрузка 9/10, жим лёжа на 2 повтора ниже плана.",
    time: "2 часа назад",
    clock: "11:42",
    dateGroup: "today",
    unread: true,
  },
  {
    id: "activity-2",
    clientId: "maria-volkova",
    clientName: "Мария Волкова",
    type: "personal_record",
    title: "Мария поставила личный рекорд",
    description: "Румынская тяга 62,5 кг на 8 повторений.",
    time: "сегодня",
    clock: "10:15",
    dateGroup: "today",
    unread: true,
  },
  {
    id: "activity-3",
    clientId: "olga-sokolova",
    clientName: "Ольга Соколова",
    type: "check_in_submitted",
    title: "Ольга отправила чек-ин",
    description: "Отметила усталость плеч после тяговой тренировки.",
    time: "сегодня",
    clock: "09:31",
    dateGroup: "today",
    unread: true,
  },
  {
    id: "activity-4",
    clientId: "dmitry-korolev",
    clientName: "Дмитрий Королёв",
    type: "workout_assigned",
    title: "Дмитрий получил следующую тренировку",
    description: "Силовой верх назначена на завтра.",
    time: "сегодня",
    clock: "08:47",
    dateGroup: "today",
  },
  {
    id: "activity-5",
    clientId: "sofia-andreeva",
    clientName: "София Андреева",
    type: "review_sent",
    title: "Софии отправлен разбор",
    description: "Скорректировали темп и объём на следующую неделю.",
    time: "сегодня",
    clock: "08:12",
    dateGroup: "today",
  },
  {
    id: "activity-6",
    clientId: "nikita-ivanov",
    clientName: "Никита Иванов",
    type: "completed_workout",
    title: "Никита завершил Фокус на присед",
    description: "Все рабочие подходы выполнены, RPE 8/10.",
    time: "сегодня",
    clock: "07:58",
    dateGroup: "today",
  },
  {
    id: "activity-7",
    clientId: "anna-petrova",
    clientName: "Анна Петрова",
    type: "measurement_updated",
    title: "Анна обновила замеры",
    description: "Талия −1,2 см за неделю, вес стабилен.",
    time: "сегодня",
    clock: "07:36",
    dateGroup: "today",
    unread: true,
  },
  {
    id: "activity-8",
    clientId: "kirill-orlov",
    clientName: "Кирилл Орлов",
    type: "check_in_submitted",
    title: "Кирилл отправил чек-ин",
    description: "Сон 7 часов, энергия 8/10, без жалоб.",
    time: "сегодня",
    clock: "07:20",
    dateGroup: "today",
  },
  {
    id: "activity-9",
    clientId: "pavel-sergeev",
    clientName: "Павел Сергеев",
    type: "message_received",
    title: "Павел написал по питанию",
    description: "Спросил, как заменить ужин в день командировки.",
    time: "сегодня",
    clock: "06:55",
    dateGroup: "today",
    unread: true,
  },
  {
    id: "activity-10",
    clientId: "roman-belov",
    clientName: "Роман Белов",
    type: "completed_workout",
    title: "Роман завершил День жима",
    description: "Объём выполнен полностью, последний сет уверенный.",
    time: "сегодня",
    clock: "06:28",
    dateGroup: "today",
  },
  {
    id: "activity-11",
    clientId: "elena-kuznetsova",
    clientName: "Елена Кузнецова",
    type: "measurement_updated",
    title: "Елена обновила вес",
    description: "Вес без изменений, ритм тренировок сохранён.",
    time: "сегодня",
    clock: "06:08",
    dateGroup: "today",
  },
  {
    id: "activity-12",
    clientId: "ivan-melnikov",
    clientName: "Иван Мельников",
    type: "workout_assigned",
    title: "Иван получил День тяги",
    description: "Следующая тренировка назначена на вечер.",
    time: "сегодня",
    clock: "05:42",
    dateGroup: "today",
  },
  {
    id: "activity-13",
    clientId: "egor-nikitin",
    clientName: "Егор Никитин",
    type: "completed_workout",
    title: "Егор завершил стартовую тренировку",
    description: "Первый день после паузы закрыт без жалоб.",
    time: "вчера",
    clock: "21:18",
    dateGroup: "yesterday",
    unread: true,
  },
  {
    id: "activity-14",
    clientId: "veronika-levina",
    clientName: "Вероника Левина",
    type: "check_in_submitted",
    title: "Вероника отправила чек-ин",
    description: "Спина чувствует себя лучше, растяжка помогает.",
    time: "вчера",
    clock: "20:44",
    dateGroup: "yesterday",
  },
  {
    id: "activity-15",
    clientId: "timur-akimov",
    clientName: "Тимур Акимов",
    type: "personal_record",
    title: "Тимур обновил рекорд в тяге",
    description: "Тяга 130 кг на 3 повторения.",
    time: "вчера",
    clock: "19:52",
    dateGroup: "yesterday",
  },
  {
    id: "activity-16",
    clientId: "alisa-zvereva",
    clientName: "Алиса Зверева",
    type: "measurement_updated",
    title: "Алиса загрузила замеры",
    description: "Фото и объёмы обновлены перед новой неделей.",
    time: "вчера",
    clock: "18:37",
    dateGroup: "yesterday",
  },
  {
    id: "activity-17",
    clientId: "maxim-ustinov",
    clientName: "Максим Устинов",
    type: "completed_workout",
    title: "Максим завершил Тяжёлый низ",
    description: "Присед выполнен по плану, RPE 8/10.",
    time: "вчера",
    clock: "17:20",
    dateGroup: "yesterday",
  },
  {
    id: "activity-18",
    clientId: "polina-gromova",
    clientName: "Полина Громова",
    type: "message_received",
    title: "Полина оставила комментарий",
    description: "Спросила, можно ли заменить выпад на жим ногами.",
    time: "вчера",
    clock: "16:12",
    dateGroup: "yesterday",
    unread: true,
  },
  {
    id: "activity-19",
    clientId: "irina-kozlova",
    clientName: "Ирина Козлова",
    type: "workout_assigned",
    title: "Ирина получила Полное тело B",
    description: "Тренировка назначена на завтра утром.",
    time: "вчера",
    clock: "15:30",
    dateGroup: "yesterday",
  },
  {
    id: "activity-20",
    clientId: "leonid-savin",
    clientName: "Леонид Савин",
    type: "review_sent",
    title: "Леониду отправлен разбор",
    description: "Уточнили технику в тяге верхнего блока.",
    time: "вчера",
    clock: "14:05",
    dateGroup: "yesterday",
  },
  {
    id: "activity-21",
    clientId: "yana-fedotova",
    clientName: "Яна Федотова",
    type: "check_in_submitted",
    title: "Яна отправила чек-ин",
    description: "Энергия 7/10, восстановление нормальное.",
    time: "вчера",
    clock: "12:42",
    dateGroup: "yesterday",
  },
  {
    id: "activity-22",
    clientId: "ksenia-belyaeva",
    clientName: "Ксения Беляева",
    type: "message_received",
    title: "Ксения предупредила о паузе",
    description: "На этой неделе плотный рабочий график.",
    time: "вчера",
    clock: "11:28",
    dateGroup: "yesterday",
  },
  {
    id: "activity-23",
    clientId: "natalia-ershova",
    clientName: "Наталья Ершова",
    type: "measurement_updated",
    title: "Наталья обновила вес",
    description: "Вес стабилен, восстановление продолжается.",
    time: "вчера",
    clock: "09:40",
    dateGroup: "yesterday",
  },
  {
    id: "activity-24",
    clientId: "vadim-larin",
    clientName: "Вадим Ларин",
    type: "message_received",
    title: "Вадим написал из командировки",
    description: "Попросил перенести старт недели.",
    time: "вчера",
    clock: "08:18",
    dateGroup: "yesterday",
  },
  {
    id: "activity-25",
    clientId: "maria-volkova",
    clientName: "Мария Волкова",
    type: "completed_workout",
    title: "Мария завершила Низ тела",
    description: "Тренировка закрыта полностью, RPE 7/10.",
    time: "на неделе",
    clock: "Пн 20:34",
    dateGroup: "week",
  },
  {
    id: "activity-26",
    clientId: "artem-smirnov",
    clientName: "Артём Смирнов",
    type: "message_received",
    title: "Артём прокомментировал жим",
    description: "Последний подход дался тяжелее обычного.",
    time: "на неделе",
    clock: "Пн 19:11",
    dateGroup: "week",
  },
  {
    id: "activity-27",
    clientId: "olga-sokolova",
    clientName: "Ольга Соколова",
    type: "measurement_updated",
    title: "Ольга обновила замеры",
    description: "Плечевой пояс без визуального отёка.",
    time: "на неделе",
    clock: "Пн 18:20",
    dateGroup: "week",
  },
  {
    id: "activity-28",
    clientId: "dmitry-korolev",
    clientName: "Дмитрий Королёв",
    type: "personal_record",
    title: "Дмитрий обновил рабочий вес",
    description: "Жим гантелей 34 кг на 9 повторений.",
    time: "на неделе",
    clock: "Пн 17:03",
    dateGroup: "week",
  },
  {
    id: "activity-29",
    clientId: "sofia-andreeva",
    clientName: "София Андреева",
    type: "check_in_submitted",
    title: "София отправила недельный отчёт",
    description: "Просит оставить объём без изменений.",
    time: "на неделе",
    clock: "Пн 15:56",
    dateGroup: "week",
  },
  {
    id: "activity-30",
    clientId: "nikita-ivanov",
    clientName: "Никита Иванов",
    type: "workout_assigned",
    title: "Никита получил день приседа",
    description: "Добавлен один разминочный подход.",
    time: "на неделе",
    clock: "Пн 14:22",
    dateGroup: "week",
  },
  {
    id: "activity-31",
    clientId: "anna-petrova",
    clientName: "Анна Петрова",
    type: "completed_workout",
    title: "Анна завершила Полное тело",
    description: "Кардио после силовой выполнено 12 минут.",
    time: "на неделе",
    clock: "Пн 13:44",
    dateGroup: "week",
  },
  {
    id: "activity-32",
    clientId: "kirill-orlov",
    clientName: "Кирилл Орлов",
    type: "review_sent",
    title: "Кириллу отправлен разбор",
    description: "Попросили держать паузу в нижней точке.",
    time: "на неделе",
    clock: "Пн 12:05",
    dateGroup: "week",
  },
  {
    id: "activity-33",
    clientId: "elena-kuznetsova",
    clientName: "Елена Кузнецова",
    type: "completed_workout",
    title: "Елена завершила Кондицию",
    description: "Темп ровный, дыхание без срывов.",
    time: "на неделе",
    clock: "Вс 19:48",
    dateGroup: "week",
  },
  {
    id: "activity-34",
    clientId: "roman-belov",
    clientName: "Роман Белов",
    type: "personal_record",
    title: "Роман улучшил лучший сет",
    description: "Жим 92,5 кг на 4 повторения.",
    time: "на неделе",
    clock: "Вс 18:14",
    dateGroup: "week",
  },
  {
    id: "activity-35",
    clientId: "polina-gromova",
    clientName: "Полина Громова",
    type: "measurement_updated",
    title: "Полина обновила вес",
    description: "Минус 0,4 кг за неделю.",
    time: "на неделе",
    clock: "Вс 16:36",
    dateGroup: "week",
  },
  {
    id: "activity-36",
    clientId: "ivan-melnikov",
    clientName: "Иван Мельников",
    type: "check_in_submitted",
    title: "Иван отправил чек-ин",
    description: "Сон просел, нагрузку пока не повышаем.",
    time: "на неделе",
    clock: "Вс 15:10",
    dateGroup: "week",
  },
  {
    id: "activity-37",
    clientId: "alisa-zvereva",
    clientName: "Алиса Зверева",
    type: "completed_workout",
    title: "Алиса завершила Лёгкий верх",
    description: "Движения без дискомфорта, RPE 6/10.",
    time: "на неделе",
    clock: "Вс 13:25",
    dateGroup: "week",
  },
  {
    id: "activity-38",
    clientId: "maxim-ustinov",
    clientName: "Максим Устинов",
    type: "workout_assigned",
    title: "Максим получил тяжёлый низ",
    description: "Рабочие веса оставлены без повышения.",
    time: "на неделе",
    clock: "Вс 11:52",
    dateGroup: "week",
  },
  {
    id: "activity-39",
    clientId: "veronika-levina",
    clientName: "Вероника Левина",
    type: "review_sent",
    title: "Веронике отправлен разбор",
    description: "Добавлен фокус на нейтральное положение таза.",
    time: "на неделе",
    clock: "Сб 18:44",
    dateGroup: "week",
  },
  {
    id: "activity-40",
    clientId: "pavel-sergeev",
    clientName: "Павел Сергеев",
    type: "completed_workout",
    title: "Павел завершил Метаболическую",
    description: "Пульс держался в целевой зоне.",
    time: "на неделе",
    clock: "Сб 17:31",
    dateGroup: "week",
  },
  {
    id: "activity-41",
    clientId: "yana-fedotova",
    clientName: "Яна Федотова",
    type: "measurement_updated",
    title: "Яна обновила замеры",
    description: "Фото прогресса добавлены в профиль.",
    time: "на неделе",
    clock: "Сб 12:16",
    dateGroup: "week",
  },
  {
    id: "activity-42",
    clientId: "leonid-savin",
    clientName: "Леонид Савин",
    type: "workout_assigned",
    title: "Леонид получил стартовую силовую",
    description: "Первая тренировка после отпуска назначена.",
    time: "на неделе",
    clock: "Сб 10:02",
    dateGroup: "week",
  },
];

export const secondaryAttentionItems: SecondaryAttentionItem[] = [
  {
    id: "no-measurements",
    label: "Нет замеров",
    count: 4,
    helper: "Попросить обновить фото и объёмы",
    icon: Ruler,
  },
  {
    id: "no-check-in",
    label: "Нет чек-ина",
    count: 2,
    helper: "Мягко напомнить о недельном отчёте",
    icon: ClipboardCheck,
  },
  {
    id: "no-weight-update",
    label: "Не обновляли вес",
    count: 3,
    helper: "Проверить динамику перед правкой плана",
    icon: Scale,
  },
  {
    id: "no-message-response",
    label: "Не ответили в сообщении",
    count: 1,
    helper: "Вернуть клиента в диалог",
    icon: MessageCircle,
  },
];

export function getTeamSummary(clients: TeamClient[]): TeamSummary {
  return {
    total: clients.length,
    onTrack: clients.filter((client) => client.state === "on_track").length,
    needsAction: clients.filter((client) => ["no_next_workout", "waiting_review", "needs_adjustment"].includes(client.state)).length,
    waitingReview: clients.filter((client) => client.state === "waiting_review").length,
    noNextWorkout: clients.filter((client) => client.state === "no_next_workout").length,
    inactive: clients.filter((client) => client.state === "inactive").length,
  };
}

export function getCalmTeam(clients: TeamClient[]): TeamClient[] {
  return clients.map((client) => ({
    ...client,
    state: client.state === "inactive" ? "inactive" : "on_track",
    stateLabel: client.state === "inactive" ? "Пауза" : "По плану",
    issue: undefined,
    context: undefined,
    primaryAction: undefined,
  }));
}
